ridgeback_vel_traj_controller:
   type: velocity_controllers/JointTrajectoryController
   joints:
     - x
     - y
     - angle
   gains:
      x:     {p: 1.0,  i: 0.0, d: 0.0, i_clamp: 1}
      y:     {p: 1.0,  i: 0.0, d: 0.0, i_clamp: 1}
      angle: {p: 1.0,  i: 0.0, d: 0.0, i_clamp: 1}
   # Use a feedforward term to reduce the size of PID gains
   velocity_ff:
      shoulder_pan_joint: 1.0
      shoulder_lift_joint: 1.0
      elbow_joint: 1.0
      wrist_1_joint: 1.0
      wrist_2_joint: 1.0
      wrist_3_joint: 1.0
   stop_trajectory_duration: 0.5
   state_publish_rate: 100
   action_monitor_rate: 100
