include:
  -
    key: simulation
    package: upright_cmd
    path: config/simulation.yaml
  -
    key: controller
    package: upright_cmd
    path: config/controller.yaml
  -
    package: upright_cmd
    path: config/robots/thing.yaml
  -
    package: upright_cmd
    path: config/ral23/simulations/_base.yaml

simulation:
  arrangement: tall_simulation_box

controller:
  # keep this so that we use the correct controller arrangement for later
  # logging/analysis
  balancing:
    enabled: false
    use_force_constraints: true
    arrangement: tall_simulation_box

  inertial_alignment:
    cost_enabled: false
    constraint_enabled: true
    use_angular_acceleration: false
    align_with_fixed_vector: false
    cost_weight: 10
    contact_plane_normal: [0, 0, 1]
    alpha: 0
    com: [0, 0, 0]
