include:
  -
    key: simulation
    package: upright_cmd
    path: config/simulation.yaml
  -
    key: controller
    package: upright_cmd
    path: config/controller.yaml
  -
    package: upright_cmd
    path: config/robots/thing.yaml
  -
    package: upright_cmd
    path: config/ral23/simulations/_base.yaml
