# arrangements reference the objects below
# arrangements are used for both simulation and the controller, but the one
# used in each can be different
arrangements:
  nothing:
    objects: []

  box_arch:
    objects:
      -
        name: block1
        type: wood_block_rotx
        parent: ee
        offset:
          y: 0.0325
      -
        name: block2
        type: wood_block_rotx
        parent: ee
        offset:
          y: -0.0325
      -
        name: block3
        type: wood_block_rotz
        parent: block2
        offset:
          y: 0.0325
    contacts:
      -
        first: ee
        second: block1
        mu: 0.27
      -
        first: ee
        second: block2
        mu: 0.27
      -
        first: block1
        second: block3
        mu: 0.27  # TODO measure
      -
        first: block2
        second: block3
        mu: 0.27  # TODO measure

  # single water bottle
  bottle:
    objects:
      -
        name: bottle1
        type: bottle
        parent: ee
        offset:
          y: -0.06
    contacts:
      -
        first: ee
        second: bottle1
        mu: 0.15

  # single foam die
  foam_die1:
    mu_margin: 0.05
    support_area_inset: 0.01
    objects:
      -
        name: foam_die1
        type: foam_die
        parent: ee
        offset:
          y: -0.06
    contacts:
      -
        first: ee
        second: foam_die1
        mu: 0.4

  # two foam dice stacked atop one another
  foam_die2:
    mu_margin: 0.05
    support_area_inset: 0.01
    objects:
      -
        name: foam_die1
        type: foam_die
        parent: ee
        offset:
          y: -0.06
      -
        name: foam_die2
        type: foam_die
        parent: foam_die1
    contacts:
      -
        first: ee
        second: foam_die1
        mu: 0.4
      -
        first: foam_die1
        second: foam_die2
        mu: 0.4  # TODO measure

  tall_box:
    support_area_inset: 0.01
    mu_margin: 0.01
    objects:
      -
        name: box1
        type: tall_box
        parent: ee
    contacts:
      -
        first: ee
        second: box1
        mu: 0.1

  simulation_bottle:
    objects:
      -
        name: bottle
        type: simulation_bottle
        parent: ee
    contacts:
      -
        first: ee
        second: bottle
        mu: 0.3
        support_area_inset: 0.005
        mu_margin: 0.01

  simulation_bottle_with_fixture:
    objects:
      -
        name: bottle
        type: simulation_bottle
        parent: ee
      -
        name: fixture
        type: fixture
        parent: ee
        fixture: true
        offset:
          y: -0.055
    contacts:
      -
        first: ee
        second: bottle
        mu: 0.3
        support_area_inset: 0.005
        mu_margin: 0.01
      -
        first: fixture
        second: bottle
        mu: 0.3
        mu_margin: 0.01

  tall_simulation_bottle:
    support_area_inset: 0.005
    mu_margin: 0.01
    objects:
      -
        name: bottle
        type: tall_simulation_bottle
        parent: ee
    contacts:
      -
        first: ee
        second: bottle
        mu: 0.3
        support_area_inset: 0.005
        mu_margin: 0.01

  wood_block_composite:
    support_area_inset: 0.01
    mu_margin: 0.01
    objects:
      -
        name: block1
        type: wood_block_rotx
        parent: ee
        offset:
          y: 0.0325
      -
        name: block2
        type: wood_block_rotx
        parent: ee
        offset:
          y: -0.0325
      -
        name: block3
        type: wood_block_composite
        parent: ee
    contacts:
      -
        first: ee
        second: block1
        mu: 0.27
      -
        first: ee
        second: block2
        mu: 0.27
      -
        first: ee
        second: block3
        mu: 0.27  # TODO measure

  bottle_and_tall_box:
    objects:
      -
        name: box1
        type: tall_box
        parent: ee
      -
        name: bottle1
        type: bottle
        parent: ee
        offset:
          y: -0.065
    contacts:
      -
        first: ee
        second: bottle1
        mu: 0.15
      -
        first: ee
        second: box1
        mu: 0.4
      -
        first: bottle1
        second: box1
        mu: 0.15

  wedge:
    support_area_inset: 0.01
    mu_margin: 0.01
    objects:
      -
        name: wedge1
        type: wedge
        parent: ee
      -
        name: box1
        type: wood_block
        orientation: [0, 0.17580172, 0, 0.9844256]
        parent: wedge1
    contacts:
      -
        first: ee
        second: wedge1
        mu: 0.4
      -
        first: wedge1
        second: box1
        mu: 0.4

