# arrangements reference the objects below
# arrangements are used for both simulation and the controller, but the one
# used in each can be different
arrangements:
  nothing:
    objects: []

  one_box:
    objects:
      -
        name: box1
        type: cube
        offset:
          x: 0.1
          y: 0.1

  two_box:
    objects:
      -
        name: box1
        type: cube
        offset:
          x: 0.1
          y: 0.1
      -
        name: box2
        type: cube
        parent: box1

  experimental_boxes:
    objects:
      -
        name: block1
        type: wood_block
        orientation: [0.707, 0, 0, 0.707]
        parent: ee
        offset:
          x: 0.08
          y: 0.15
      -
        name: block2
        type: wood_block
        orientation: [0.707, 0, 0, 0.707]
        parent: ee
        offset:
          x: 0.08
          y: 0.09
      -
        name: block3
        type: wood_block
        orientation: [0, 0, 0.707, 0.707]
        parent: block2
        offset:
          x: 0
          y: 0.03
    contacts:
      -
        first: ee
        second: block1
        mu: 0.27
      -
        first: ee
        second: block2
        mu: 0.27
      -
        first: block1
        second: block3
        mu: 0.27  # TODO measure
      -
        first: block2
        second: block3
        mu: 0.27  # TODO measure


  # single water bottle
  bottle:
    objects:
      -
        name: bottle1
        type: bottle
        offset:
          y: -0.06
    contacts:
      -
        first: ee
        second: foam_die1
        mu: 0.15


  # single foam die
  foam_die1:
    objects:
      -
        name: foam_die1
        type: foam_die
        parent: ee
        offset:
          x: -0.1
          y: -0.13
    contacts:
      -
        first: ee
        second: foam_die1
        mu: 0.4


  # two foam dice stacked atop one another
  foam_die2:
    support_area_inset: 0.01
    objects:
      -
        name: foam_die1
        type: foam_die
        parent: ee
        offset:
          # x: 0
          # y: -0.06
          x: -0.1
          y: -0.13
          # x: -0.1
          # y: -0.1
      -
        name: foam_die2
        type: foam_die
        parent: foam_die1
    contacts:
      -
        first: ee
        second: foam_die1
        mu: 0.4
      -
        first: foam_die1
        second: foam_die2
        mu: 0.4  # TODO measure
