include:
  -
    package: upright_cmd
    path: config/arrangements.yaml

# compute a new control policy every `control_period` seconds
timestep: 0.025
use_noisy_state_to_plan: true
gravity: [0, 0, -9.81]

solver_method: SQP  # only SQP is supported now

# model predictive controller
mpc:
  time_horizon: 1.0
  debug_print: true
  cold_start: false

# trajectory rollout
rollout:
  abs_tol_ode: 1e-5
  rel_tol_ode: 1e-3
  timestep: 0.01
  max_num_steps_per_second: 100000
  check_numerical_stability: false

# low-level reference tracking
tracking:
  rate: 125  # Hz
  min_policy_update_time: 0.01  # seconds

  enforce_state_limits: true
  enforce_input_limits: false
  enforce_ee_position_limits: false

  state_violation_margin: 0.1
  input_violation_margin: 1.0
  ee_position_violation_margin: 0.1

# sequential quadratic programming
sqp:
  dt: 0.1
  sqp_iteration: 2
  init_sqp_iteration: 2
  delta_tol: 1e-3
  cost_tol: 1e-4
  use_feedback_policy: false
  project_state_input_equality_constraints: false
  print_solver_status: true
  print_solver_statistics: true
  print_line_search: true
  hpipm:
    iter_max: 30
    warm_start: true
    slacks:
      enabled: true

balancing:
  arrangement: nothing
  constraint_type: hard
  enabled: false
  use_force_constraints: false
  frictionless: true
  use_bounded_constraints: true
  enable_normal_constraint: true
  enable_friction_constraint: true
  enable_zmp_constraint: true

  force_weight: 0.001

  mu: 1e-3
  delta: 1e-3

inertial_alignment:
  cost_enabled: false
  constraint_enabled: false
  use_angular_acceleration: false
  use_constraint: true
  cost_weight: 1
  contact_plane_normal: [0, 0, 1]
  com: [0, 0, 0]

end_effector_box_constraint:
  enabled: false
  xyz_lower: [-1., -1., -0.5]
  xyz_upper: [1., 1., 0.5]

# desired waypoints are set relative to the initial EE pose
# each waypoint consists of:
#   millis: time from beginning of trajectory in milliseconds
#   position: [x, y, z] end effector position
#   orientation: [x, y, z, w] end effector orientation quaternion
# waypoints:
#   -
#     millis: 0
#     position: [2.0, 0.0, 0.0]
#     orientation: [0.0, 0.0, 0.0, 1.0]

obstacles:
  enabled: false
  constraint_type: hard

  # extra margin between objects
  # Important: this needs to be > 0 for the resulting constraint to be
  # differentiable
  minimum_distance: 0.1

  # relaxed barrier function parameters
  mu: 1e-2
  delta: 1e-3

operating_points:
  enabled: false

infofile:
  package: "upright_control"
  path: "config/mpc/task.info"

# NOTE: for now we assume inertia is exact, but we should use parallel axis
# theorem to account for com_offset
objects:
  # EE is a special object

  # wood tray
  ee:
    shape:
      type: cuboid
      side_lengths: [0.285, 0.285, 0.02]
    position: [0, 0, -0.01]  # box centroid relative to r_ew_w

  # box tray
  # ee:
  #   shape:
  #     type: cuboid
  #     side_lengths: [0.23, 0.3, 0.064]
  #   position: [0.1, 0.13, -0.032]  # box centroid relative to r_ew_w

  # restaurant tray
  # ee:
  #   shape:
  #     type: cuboid
  #     side_lengths: [0.356, 0.356, 0.01]
  #   position: [0.064, 0.127, -0.005]  # box centroid relative to r_ew_w

  cube:
    mass: 1.0
    com_offset: [0, 0, 0]
    shape:
        type: cuboid
        side_lengths: [0.1, 0.1, 0.01]

  bottle:
    mass: 0.5
    com_offset: [0, 0, 0]
    # TODO revise this
    shape:
      type: cylinder
      radius: 0.0325
      height: 0.15

  tall_bottle:
    mass: 0.72
    com_offset: [0, 0, 0]
    shape:
      type: cylinder
      radius: 0.035
      height: 0.205

  wood_block:
    mass: 0.18
    com_offset: [0, 0, 0]  # relative to centroid of shape
    shape:
      type: cuboid
      side_lengths: [0.103, 0.09, 0.038]

  wood_block_rotx:
    mass: 0.18
    com_offset: [0, 0, 0]
    shape:
      type: cuboid
      side_lengths: [0.103, 0.038, 0.09]

  wood_block_rotz:
    mass: 0.18
    com_offset: [0, 0, 0]
    shape:
      type: cuboid
      side_lengths: [0.09, 0.103, 0.038]

  wood_block_composite:
    mass: 0.54
    com_offset: [0, 0, 0]
    shape:
      type: cuboid
      side_lengths: [0.103, 0.103, 0.128]

  foam_die:
    mass: 0.02
    com_offset: [0, 0, 0]
    shape:
      type: cuboid
      side_lengths: [0.065, 0.065, 0.065]

  tall_box:
    mass: 0.04
    com_offset: [0, 0, 0]
    shape:
      type: cuboid
      side_lengths: [0.065, 0.065, 0.13]

  really_tall_box:
    mass: 0.5
    com_offset: [0, 0, 0]
    shape:
      type: cylinder
      height: 0.205
      # height: 0.5
      radius: 0.035

  wedge:
    mass: 0.09
    com_offset: [0, 0, 0]
    shape:
      type: right_triangular_prism
      side_lengths: [0.103, 0.09, 0.038]

  fixture:
    mass: 0.1
    com_offset: [0, 0, 0]
    shape:
      type: cuboid
      side_lengths: [0.05, 0.05, 0.05]

  simulation_box:
    shape:
      type: cuboid
      side_lengths: [0.06, 0.06, 0.2]
    com_offset: [0, 0, 0]
    mass: 0.5

  simulation_box_h0:
    shape:
      type: cuboid
      side_lengths: [0.06, 0.06, 0.2]
    com_offset: [0, 0, -0.1]
    mass: 0.5

  tall_simulation_box:
    shape:
      type: cuboid
      side_lengths: [0.06, 0.06, 0.64]
    com_offset: [0, 0, 0]
    mass: 0.5
