include:
  -
    package: upright_cmd
    path: config/arrangements.yaml

# compute a new control policy every `control_period` seconds
timestep: 0.025
use_noisy_state_to_plan: true
gravity: [0, 0, -9.81]
solver_method: SQP  # SQP or DDP

balancing:
  arrangement: nothing
  enabled: true
  use_bounded_constraints: true
  enable_normal_constraint: true
  enable_friction_constraint: true
  enable_zmp_constraint: true

  mu: 1e-3
  delta: 1e-3

inertial_alignment:
  enabled: false
  use_angular_acceleration: false
  weight: 10

# needs to be implemented for each particular system
tracking:
  rate: 125
  Kp: null

# desired waypoints are set relative to the initial EE pose
# each waypoint consists of:
#   millis: time from beginning of trajectory in milliseconds
#   position: [x, y, z] end effector position
#   orientation: [x, y, z, w] end effector orientation quaternion
# waypoints:
#   -
#     millis: 0
#     position: [2.0, 0.0, 0.0]
#     orientation: [0.0, 0.0, 0.0, 1.0]

static_obstacles:
  enabled: false
  urdf:
    package: "upright_assets"
    path: "urdf/obstacles.urdf"

dynamic_obstacles:
  enabled: false

infofile:
  package: "upright_control"
  path: "config/mpc/task.info"

# TODO: ideally would be able to extend other objects for easy experimentation
objects:
  ee:
    height: 0.04
    mu: 1.0

  tray:
    mass:
      min: 0.5
      max: 0.5
    com:
      height: 0.01
      half_lengths: [0.0, 0.0, 0.0]
    radii_of_gyration:
      use_exact:
        shape: cylinder
        height: 0.02
        radius: 0.2
    mu_min: 2.0
    support_area:
      shape: "circle"
      radius: 0.2
    height: 0.02

  cup:
    mass:
      min: 0.5
      max: 0.5
    com:
      height: 0.1
      half_lengths: [0.0, 0.0, 0.0]
    radii_of_gyration:
      use_exact:
        shape: cylinder
        height: 0.2
        radius: 0.04
    mu_min: 0.5
    support_area:
      shape: "circle"
      radius: 0.04
    height: 0.2

  box:
    mass:
      min: 1.0
      max: 1.0
    com:
      height: 0.075
      half_lengths: [0.0, 0.0, 0.0]
    radii_of_gyration:
      use_exact:
        shape: cuboid
        side_lengths: [0.08, 0.08, 0.15]
    mu_min: 0.5
    support_area:
      shape: "rect"
      lx: 0.08
      ly: 0.08
    height: 0.15

  cube:
    mass:
      min: 1.0
      max: 1.0
    com:
      height: 0.0
      half_lengths: [0.0, 0.0, 0.0]
    radii_of_gyration:
      use_exact:
        shape: cuboid
        side_lengths: [0.1, 0.1, 0.05]
    mu_min: 2
    support_area:
      shape: "rect"
      lx: 0.1
      ly: 0.1
    height: 0.05

  tall_box:
    mass:
      min: 1.0
      max: 1.0
    com:
      height: 0.25
      half_lengths: [0.0, 0.0, 0.0]
    radii_of_gyration:
      use_exact:
        shape: cuboid
        side_lengths: [0.06, 0.06, 0.5]
    mu_min: 0.5
    support_area:
      shape: "rect"
      lx: 0.06
      ly: 0.06
    height: 0.5

  cylinder_stack_base:
    mass:
      min: 0.75
      max: 0.75
    com:
      height: 0.05
      half_lengths: [0.0, 0.0, 0.0]
    radii_of_gyration:
      use_exact:  # TODO still not sure about this format
        shape: cylinder
        height: 0.1
        radius: 0.15
      min: [0, 0, 0]
      max: [0.15, 0.15, 0.15]
    mu_min: 0.25
    support_area:
      shape: "eq_tri"
      side_length: 0.2
    height: 0.1  # this is only used to compute relative heights

  cuboid1_stack:
    mass:
      min: 0.75
      max: 0.75
    com:
      height: 0.075
      half_lengths: [0.0, 0.0, 0.0]
    radii_of_gyration:
      use_exact:
        shape: cuboid
        side_lengths: [0.15, 0.15, 0.15]
      min: [0, 0, 0]
      max: [0.075, 0.075, 0.075]
    mu_min: 0.25
    support_area:
      shape: "rect"
      lx: 0.15
      ly: 0.15
    height: 0.15
