include:
  -
    package: upright_cmd
    path: config/arrangements.yaml
  -
    key: obstacles
    package: upright_cmd
    path: config/controller/obstacles/dynamic.yaml

# compute a new control policy every `control_period` seconds
timestep: 0.025
use_noisy_state_to_plan: true
gravity: [0, 0, -9.81]
solver_method: SQP  # SQP or DDP

balancing:
  arrangement: nothing
  constraint_type: soft
  enabled: true
  use_force_constraints: false
  use_bounded_constraints: true
  enable_normal_constraint: true
  enable_friction_constraint: true
  enable_zmp_constraint: true

  force_weight: 0.001

  mu: 1e-3
  delta: 1e-3

inertial_alignment:
  enabled: false
  use_angular_acceleration: false
  weight: 10

# needs to be implemented for each particular system
tracking:
  rate: 125
  Kp: null

# desired waypoints are set relative to the initial EE pose
# each waypoint consists of:
#   millis: time from beginning of trajectory in milliseconds
#   position: [x, y, z] end effector position
#   orientation: [x, y, z, w] end effector orientation quaternion
# waypoints:
#   -
#     millis: 0
#     position: [2.0, 0.0, 0.0]
#     orientation: [0.0, 0.0, 0.0, 1.0]

obstacles:
  enabled: true
  constraint_type: hard

  # extra margin between objects
  # Important: this needs to be > 0 for the resulting constraint to be
  # differentiable
  minimum_distance: 0.1

  # relaxed barrier function parameters
  mu: 1e-2
  delta: 1e-3

infofile:
  package: "upright_control"
  path: "config/mpc/task.info"

# TODO: ideally would be able to extend other objects for easy experimentation
objects:
  ee:
    height: 0.04
    mu: 1.0

  tray:
    mass:
      min: 0.5
      max: 0.5
    com:
      height: 0.01
      half_lengths: [0.0, 0.0, 0.0]
    radii_of_gyration:
      use_exact:
        shape: cylinder
        height: 0.02
        radius: 0.2
    mu_min: 2.0
    support_area:
      shape: "circle"
      radius: 0.2
    height: 0.02

  cup:
    mass:
      min: 0.5
      max: 0.5
    com:
      height: 0.1
      half_lengths: [0.0, 0.0, 0.0]
    radii_of_gyration:
      use_exact:
        shape: cylinder
        height: 0.2
        radius: 0.04
    mu_min: 0.5
    support_area:
      shape: "circle"
      radius: 0.04
    height: 0.2

  box:
    mass:
      min: 1.0
      max: 1.0
    com:
      height: 0.075
      half_lengths: [0.0, 0.0, 0.0]
    radii_of_gyration:
      use_exact:
        shape: cuboid
        side_lengths: [0.08, 0.08, 0.15]
    mu_min: 0.5
    support_area:
      shape: "rect"
      lx: 0.08
      ly: 0.08
    height: 0.15

  cube:
    mass:
      min: 1.0
      max: 1.0
    com:
      height: 0.025
      half_lengths: [0.0, 0.0, 0.0]
    radii_of_gyration:
      use_exact:
        shape: cuboid
        side_lengths: [0.1, 0.1, 0.05]
    mu_min: 0.5
    support_area:
      shape: "rect"
      lx: 0.1
      ly: 0.1
    height: 0.05

  bottle:
    mass:
      min: 0.5
      max: 0.5
    com:
      height: 0.075
      half_lengths: [0, 0, 0]  # these are for the uncertainty
    radii_of_gyration:
      use_exact:
        shape: cuboid
        side_lengths: [0.065, 0.065, 0.15]
    mu_min: 0.15
    support_area:
      shape: rect
      lx: 0.065
      ly: 0.065
    height: 0.15

  foam_die:
    mass:
      min: 0.02
      max: 0.02
    com:
      height: 0.0325
      half_lengths: [0, 0, 0]  # these are for the uncertainty
    radii_of_gyration:
      use_exact:
        shape: cuboid
        side_lengths: [0.065, 0.065, 0.065]
    mu_min: 0.4
    support_area:
      shape: rect
      lx: 0.05
      ly: 0.05
    height: 0.065

  # TODO this probably only works for a single orientation
  wood_block:
    mass:
      min: 0.18
      max: 0.18
    com:
      height: 0.019
      half_lengths: [0, 0, 0]
    radii_of_gyration:
      use_exact:
        shape: cuboid
        side_lengths: [0.103, 0.09, 0.038]
    mu_min: 0.27
    support_area:
      shape: rect
      lx: 0.103
      ly: 0.09
    height: 0.038

  tall_box:
    mass:
      min: 1.0
      max: 1.0
    com:
      height: 0.25
      half_lengths: [0.0, 0.0, 0.0]
    radii_of_gyration:
      use_exact:
        shape: cuboid
        side_lengths: [0.06, 0.06, 0.5]
    mu_min: 0.5
    support_area:
      shape: "rect"
      lx: 0.06
      ly: 0.06
    height: 0.5

  cylinder_stack_base:
    mass:
      min: 0.75
      max: 0.75
    com:
      height: 0.05
      half_lengths: [0.0, 0.0, 0.0]
    radii_of_gyration:
      use_exact:  # TODO still not sure about this format
        shape: cylinder
        height: 0.1
        radius: 0.15
      min: [0, 0, 0]
      max: [0.15, 0.15, 0.15]
    mu_min: 0.25
    support_area:
      shape: "eq_tri"
      side_length: 0.2
    height: 0.1  # this is only used to compute relative heights

  cuboid1_stack:
    mass:
      min: 0.75
      max: 0.75
    com:
      height: 0.075
      half_lengths: [0.0, 0.0, 0.0]
    radii_of_gyration:
      use_exact:
        shape: cuboid
        side_lengths: [0.15, 0.15, 0.15]
      min: [0, 0, 0]
      max: [0.075, 0.075, 0.075]
    mu_min: 0.25
    support_area:
      shape: "rect"
      lx: 0.15
      ly: 0.15
    height: 0.15
