include:
  -
    package: upright_cmd
    path: config/arrangements.yaml
  -
    package: upright_cmd
    path: config/simulation/cameras.yaml

# all times are in seconds
timestep: 0.001
duration: 5.0
gravity: [0, 0, -9.81]
arrangement: nothing

video:
  save_frames: true
  dir: "/media/adam/Data/PhD/Videos/upright/"
  timestep: 0.040
  views:
    -
      camera: pose_to_pose1
      name: view1

static_obstacles:
  enabled: true
  urdf:
    package: "upright_assets"
    path: "thing/urdf/obstacles.urdf"
    includes:
      - "$(find upright_assets)/thing/xacro/obstacles/simple.urdf.xacro"

dynamic_obstacles:
  enabled: false
  obstacles:
    -
      controlled: true
      position: [0, -1, 0]
      velocity: [0, 1, 2]
      acceleration: [0, 0, -2]
      radius: 0.1

objects:
  # EE is a special object
  ee:
    height: 0.0
    mu: 1.0

  tray:
    shape: cylinder
    mass: 0.5
    mu: 2.0
    height: 0.02
    radius: 0.2
    color: [0, 0, 1, 1]

  cup:
    shape: cylinder
    mass: 0.25
    mu: 0.5
    height: 0.2
    radius: 0.04
    color: [1, 0, 0, 1]

  cup_heavy:
    shape: cylinder
    mass: 1
    mu: 0.5
    height: 0.2
    radius: 0.04
    color: [1, 0, 0, 1]

  box:
    shape: "cuboid"
    mass: 1
    mu: 0.5
    side_lengths: [0.08, 0.08, 0.15]
    color: [1, 0, 0, 1]

  bottle:
    shape: "cuboid"
    mass: 0.5
    mu: 0.15
    side_lengths: [0.065, 0.065, 0.15]
    color: [0, 0, 1, 1]

  foam_die:
    shape: "cuboid"
    mass: 0.02
    mu: 0.45
    side_lengths: [0.065, 0.065, 0.065]
    color: [0, 0, 1, 1]

  box2:
    shape: "cuboid"
    mass: 0.5
    mu: 0.5
    side_lengths: [0.08, 0.08, 0.15]
    color: [1, 0, 0, 1]

  box3:
    shape: "cuboid"
    mass: 1
    mu: 0.5
    side_lengths: [0.08, 0.08, 0.15]
    color: [1, 0, 0, 1]

  box4:
    shape: "cuboid"
    mass: 2.0
    mu: 0.5
    side_lengths: [0.08, 0.08, 0.15]
    color: [1, 0, 0, 1]

  cube:
    shape: cuboid
    mass: 1.0
    mu: 1.0
    side_lengths: [0.1, 0.1, 0.05]
    color: [1, 0, 0, 1]

  tall_box:
    shape: "cuboid"
    mass: 1.0
    mu: 0.5
    side_lengths: [0.06, 0.06, 0.5]
    com_offset: [0, 0, 0]  # offset of CoM from object centroid
    color: [0, 1, 0, 1]

  cylinder_stack_base:
    shape: "cylinder"
    mass: 0.75
    mu: 0.25
    height: 0.1
    radius: 0.15
    color: [0, 0, 1, 1]

  cuboid1_stack:
    shape: "cuboid"
    mass: 0.75
    mu: 0.25
    side_lengths: [0.15, 0.15, 0.15]
    color: [1, 0, 0, 1]
