include:
  -
    package: upright_cmd
    path: config/arrangements.yaml
  -
    package: upright_cmd
    path: config/simulation/cameras.yaml

# all times are in seconds
timestep: 0.001
duration: 5.0
gravity: [0, 0, -9.81]
arrangement: nothing

video:
  save_frames: true
  dir: "/media/adam/Data/PhD/Videos/upright/"
  timestep: 0.040
  views:
    -
      camera: pose_to_pose1
      name: view1

static_obstacles:
  enabled: false
  urdf:
    package: "upright_assets"
    path: "thing/urdf/obstacles.urdf"
    includes:
      - "$(find upright_assets)/thing/xacro/obstacles/simple.urdf.xacro"

dynamic_obstacles:
  enabled: false

objects:
  # EE is a special object
  ee:
    shape:
      type: cuboid
      side_lengths: [0.23, 0.3, 0.064]
    position: [0.1, 0.13, -0.032]  # box centroid relative to r_ew_w

  bottle:
    shape: cylinder
    mass: 0.5
    radius: 0.0325
    height: 0.15
    color: [0, 0, 1, 0.9]

  foam_die:
    shape: cuboid
    mass: 0.02
    side_lengths: [0.065, 0.065, 0.065]
    color: [0, 0, 1, 1]

  wood_block:
    shape: cuboid
    mass: 0.18
    side_lengths: [0.103, 0.09, 0.038]
    color: [1, 0, 0, 0.9]

  cube:
    shape: cuboid
    mass: 1.0
    side_lengths: [0.1, 0.1, 0.05]
    color: [1, 0, 0, 1]

  tall_box:
    shape: cuboid
    mass: 0.04
    side_lengths: [0.065, 0.065, 0.13]
    color: [1, 0, 0, 0.9]

  really_tall_box:
    shape: cuboid
    mass: 0.04
    side_lengths: [0.065, 0.065, 0.3]
    color: [1, 0, 0, 0.9]
