include:
  -
    package: upright_cmd
    path: config/arrangements.yaml
  -
    package: upright_cmd
    path: config/simulation/cameras.yaml

# all times are in seconds
timestep: 0.001
duration: 5.0
gravity: [0, 0, -9.81]
arrangement: nothing

video:
  save_frames: true
  dir: "/media/adam/Data/PhD/Videos/upright/"
  timestep: 0.040
  views:
    -
      camera: pose_to_pose1
      name: view1

static_obstacles:
  enabled: false
  urdf:
    package: "upright_assets"
    path: "thing/urdf/obstacles.urdf"
    includes:
      - "$(find upright_assets)/thing/xacro/obstacles/simple.urdf.xacro"

dynamic_obstacles:
  enabled: false
  obstacles:
    # -
    #   controlled: true
    #   position: [0, -1, 0]
    #   velocity: [0, 2, 0]
    #   acceleration: [0, 0, 0]
    #   radius: 0.1
    -
      controlled: false
      position: [0, -1, 0]
      velocity: [0, 1, 5]
      acceleration: [0, 0, -9.81]
      radius: 0.1

objects:
  # EE is a special object
  ee:
    shape:
      type: cuboid
      side_lengths: [0.23, 0.3, 0.064]
    position: [0.1, 0.13, -0.032]  # box centroid relative to r_ew_w

  bottle:
    shape: cuboid
    mass: 0.5
    side_lengths: [0.065, 0.065, 0.15]
    color: [0, 0, 1, 1]

  foam_die:
    shape: cuboid
    mass: 0.02
    side_lengths: [0.065, 0.065, 0.065]
    color: [0, 0, 1, 1]

  wood_block:
    shape: cuboid
    mass: 0.18
    side_lengths: [0.103, 0.09, 0.038]
    color: [1, 0, 0, 0.9]

  cube:
    shape: cuboid
    mass: 1.0
    side_lengths: [0.1, 0.1, 0.05]
    color: [1, 0, 0, 1]
