include:
  -
    key: perls2
    package: upright_cmd
    path: config/panda/perls2/perls2.yaml
  -
    package: upright_cmd
    path: config/panda/panda.yaml

logging:
  timestep: 10
  log_dir: /media/adam/Data/PhD/Data/object-balance/real-panda
