logging:
  timestep: 0.010
  log_dir: /media/adam/Data/PhD/Data/upright/ral23/simulations

simulation:
  duration: 5.0
  arrangement: really_tall_box_with_fixture

controller:
  balancing:
    enabled: false
    use_force_constraints: true
    arrangement: really_tall_box_with_fixture
    constraint_type: hard

  weights:
    input:
      scale: 0.001
      diag: [1rep9]
    state:
      scale: 0.01
      diag: [0rep9, 10rep9, 1rep9]
    end_effector:
      scale: 1
      diag: [1, 1, 1, 0, 0, 0]

  waypoints:
    -
      time: 0
      position: [1.0, 2.0, 0]
      orientation: [0, 0, 0, 1]
