include:
  -
    key: simulation
    package: upright_cmd
    path: config/simulation.yaml
  -
    key: controller
    package: upright_cmd
    path: config/controller.yaml
  -
    package: upright_cmd
    path: config/robots/thing.yaml
  -
    package: upright_cmd
    path: config/ral23/simulations/comparisons/_base.yaml

controller:
  balancing:
    enabled: true
    use_force_constraints: true
    arrangement: really_tall_box_with_fixture
    constraint_type: hard
