include:
  -
    key: simulation
    package: upright_cmd
    path: config/simulation.yaml
  -
    key: controller
    package: upright_cmd
    path: config/controller.yaml
  -
    package: upright_cmd
    path: config/omni/omni.yaml

logging:
  timestep: 0.010
  log_dir: /media/adam/Data/PhD/Data/upright/bounded

simulation:
  duration: 10.0
  arrangement: foam_die1

controller:
  balancing:
    enabled: true
    use_force_constraints: false
    arrangement: foam_die1
    constraint_type: hard
    enable_normal_constraint: false
    enable_friction_constraint: true
    enable_zmp_constraint: false

  waypoints:
    -
      time: 0
      position: [2.0, 0.5, 0.25]
      orientation: [0, 0, 0, 1]
