include:
  -
    key: simulation
    package: upright_cmd
    path: config/simulation.yaml
  -
    key: controller
    package: upright_cmd
    path: config/controller.yaml
  -
    package: upright_cmd
    path: config/omni/omni.yaml

logging:
  timestep: 0.010
  log_dir: /media/adam/Data/PhD/Data/upright/bounded

simulation:
  duration: 10.0
  arrangement: really_tall_box

controller:
  balancing:
    enabled: true
    use_force_constraints: true
    arrangement: really_tall_box
    constraint_type: hard
    enable_normal_constraint: true
    enable_friction_constraint: true
    enable_zmp_constraint: true

  inertial_alignment:
    enabled: false
    use_constraint: true
    use_angular_acceleration: false
    contact_plane_normal: [0, 0, 1]
    com: [0, 0, 0]

  weights:
    input:
      scale: 0.001
      diag: [1rep9]
    state:
      scale: 0.01
      diag: [0rep9, 10rep9, 1rep9]
    end_effector:
      scale: 1
      diag: [1, 1, 1, 0, 0, 0]

  waypoints:
    -
      time: 0
      position: [2.0, 0.5, 0.25]
      orientation: [0, 0, 0, 1]
