simulation:
  robot:
    # home: [0, 0, 0, 0.5pi, -0.75pi, -0.5pi, -0.25pi, -0.5pi, 0.5pi]  # upright
    home: [0, 0, 0, 0.5pi, -0.25pi, 0.5pi, -0.25pi, 0.5pi, 0.417pi]  # standard
    dims:
      q: 9  # generalized position
      v: 9  # generalized velocity
      x: 27 # state
      u: 9  # input
    noise:
      measurement:
        q_std_dev: 0
        v_std_dev: 0
      process:
        v_std_dev: 0
    joint_names:
      - "x_to_world_joint"
      - "y_to_x_joint"
      - "base_to_y_joint"
      - "ur10_arm_shoulder_pan_joint"
      - "ur10_arm_shoulder_lift_joint"
      - "ur10_arm_elbow_joint"
      - "ur10_arm_wrist_1_joint"
      - "ur10_arm_wrist_2_joint"
      - "ur10_arm_wrist_3_joint"
    tool_joint_name: "gripped_object_joint"
    base_type: omnidirectional
    urdf:
      package: "upright_assets"
      path: "thing/urdf/thing_pyb.urdf"
      includes:
        - "$(find upright_assets)/thing/xacro/cartesian_base_joints.urdf.xacro"
        - "$(find mobile_manipulation_central)/urdf/xacro/thing_no_wheels.urdf.xacro"
        - "$(find upright_assets)/thing/xacro/end_effectors/gripped_object.urdf.xacro"
        - "$(find upright_assets)/thing/xacro/collision/visual_collision_links.urdf.xacro"

controller:
  # robot parameters
  robot:
    dims:
      q: 9  # generalized position
      v: 9  # generalized velocity
      x: 27 # state
      u: 9  # input
    x0: [0, 0, 0, 0.5pi, -0.25pi, 0.5pi, -0.25pi, 0.5pi, 0.417pi, 0rep9, 0rep9]
    urdf:
      package: "upright_assets"
      path: "thing/urdf/thing_ocs2.urdf"
      includes:
        - "$(find mobile_manipulation_central)/urdf/xacro/thing_no_wheels.urdf.xacro"
        - "$(find upright_assets)/thing/xacro/end_effectors/gripped_object.urdf.xacro"
        - "$(find upright_assets)/thing/xacro/collision/collision_links.urdf.xacro"
    tool_link_name: "gripped_object"
    base_type: omnidirectional

  # weights on state, input, and end effector pose
  weights:
    input:
      scale: 0.001
      diag: [1rep9]
    state:
      scale: 0.01
      diag: [0rep9, 10rep9, 1rep9]
    end_effector:
      scale: 1
      diag: [1, 1, 1, 0, 0, 0]

  # reduced state and input limits
  limits:
    constraint_type: soft
    input:
      lower: [-20, -20, -20, -80, -80, -80, -80, -80, -80]
      upper: [20, 20, 20, 80, 80, 80, 80, 80, 80]
    state:
      lower: [-10, -10, -10, -2pi, -2pi, -2pi, -2pi, -2pi, -2pi,
              -0.5rep9,
              -2rep9]
      upper: [10, 10, 10, 2pi, 2pi, 2pi, 2pi, 2pi, 2pi,
              0.5rep9,
              2rep9]

  # state and input limits
  # limits:
  #   input:
  #     lower: [-20, -20, -20, -80, -80, -80, -80, -80, -80]
  #     upper: [20, 20, 20, 80, 80, 80, 80, 80, 80]
  #   # TODO: real arm velocity limits are higher
  #   state:
  #     lower: [-10, -10, -10, -2pi, -2pi, -2pi, -2pi, -2pi, -2pi,
  #             -1.1, -1.1, -2, -2, -2, -2, -2, -2, -2,
  #             -2.5, -2.5, -1, -8, -8, -8, -8, -8, -8]
  #     upper: [10, 10, 10, 2pi, 2pi, 2pi, 2pi, 2pi, 2pi,
  #             1.1, 1.1, 2, 2, 2, 2, 2, 2, 2,
  #             2.5, 2.5, 1, 8, 8, 8, 8, 8, 8]
    # input:
    #   lower: [-200rep3, -400rep6]
    #   upper: [200rep3, 400rep6]
    # state:
    #   lower: [-10, -10, -10, -2pi, -2pi, -2pi, -2pi, -2pi, -2pi, -10, -10, -10, -20, -20, -20, -20, -20, -20, -20, -20, -20, -40, -40, -40, -40, -40, -40]
    #   upper: [10, 10, 10, 2pi, 2pi, 2pi, 2pi, 2pi, 2pi, 10, 10, 10, 20, 20, 20, 20, 20, 20, 20, 20, 20, 40, 40, 40, 40, 40, 40]
