include:
  -
    key: simulation
    package: upright_cmd
    path: config/simulation.yaml
  -
    key: controller
    package: upright_cmd
    path: config/controller.yaml
  -
    package: upright_cmd
    path: config/omni/omni.yaml

logging:
  timestep: 0.010
  log_dir: /media/adam/Data/PhD/Data/object-balance/bounded

simulation:
  duration: 10.0
  arrangement: one_box

controller:
  balancing:
    enabled: false
    arrangement: one_box

  tracking:
    rate: 125
    Kp:
      scale: 1
      diag: [1rep9]

  waypoints:
    -
      time: 0
      position: [0.0, 0.3, 0.0]
      orientation: [0, 0, 0, 1]

  operating_points:
    enabled: false
