include:
  -
    key: simulation
    package: upright_cmd
    path: config/simulation.yaml
  -
    key: controller
    package: upright_cmd
    path: config/controller.yaml
  -
    package: upright_cmd
    path: config/omni/omni.yaml
  -
    package: upright_cmd
    path: config/obstacles/dynamic.yaml

logging:
  timestep: 0.010
  log_dir: /media/adam/Data/PhD/Data/upright/bounded

simulation:
  duration: 10.0
  arrangement: foam_die1

  dynamic_obstacles:
    enabled: true

controller:
  balancing:
    enabled: true
    use_force_constraints: false
    arrangement: foam_die1
    constraint_type: hard
    enable_normal_constraint: true
    enable_friction_constraint: true
    enable_zmp_constraint: true

  weights:
    end_effector:
      scale: 0.1
      diag: [1, 1, 1, 0, 0, 0]

  obstacles:
    enabled: true
    constraint_type: hard
    minimum_distance: 0.2

  end_effector_box_constraint:
    enabled: true
    xyz_lower: [-1., -1., -0.5]
    xyz_upper: [1., 1., 0.5]

  waypoints:
    -
      time: 0
      position: [0, 0, 0]
      orientation: [0, 0, 0, 1]

  limits:
    constraint_type: hard
    input:
      lower: [-20, -20, -20, -80, -80, -80, -80, -80, -80]
      upper: [20, 20, 20, 80, 80, 80, 80, 80, 80]
    state:
      lower: [-10, -10, -10, -2pi, -2pi, -2pi, -2pi, -2pi, -2pi,
              -1.1, -1.1, -2, -2, -2, -2, -2, -2, -2,
              -2.5, -2.5, -1, -8, -8, -8, -8, -8, -8]
      upper: [10, 10, 10, 2pi, 2pi, 2pi, 2pi, 2pi, 2pi,
              1.1, 1.1, 2, 2, 2, 2, 2, 2, 2,
              2.5, 2.5, 1, 8, 8, 8, 8, 8, 8]
