include:
  -
    key: simulation
    package: upright_cmd
    path: config/simulation.yaml
  -
    key: controller
    package: upright_cmd
    path: config/controller.yaml
  -
    package: upright_cmd
    path: config/omni/omni.yaml

logging:
  timestep: 0.010
  log_dir: /media/adam/Data/PhD/Data/upright/bounded

simulation:
  duration: 10.0
  arrangement: box_arch

controller:
  balancing:
    enabled: true
    use_force_constraints: true
    arrangement: box_arch
    constraint_type: hard
    enable_normal_constraint: true
    enable_friction_constraint: true
    enable_zmp_constraint: true

  tracking:
    rate: 125
    Kp:
      scale: 1
      diag: [1rep9]

  waypoints:
    # -
    #   time: 0
    #   position: [0, 0, 0]
    #   orientation: [0, 0, 0, 1]
    -
      time: 0
      position: [2.0, 0.5, 0.25]
      orientation: [0, 0, 0, 1]

  operating_points:
    enabled: false
