include:
  -
    key: simulation
    package: upright_cmd
    path: config/simulation.yaml
  -
    key: controller
    package: upright_cmd
    path: config/controller.yaml
  -
    package: upright_cmd
    path: config/omni/omni.yaml
  -
    package: upright_cmd
    path: config/obstacles/simple.yaml

logging:
  timestep: 0.010
  log_dir: /media/adam/Data/PhD/Data/upright/bounded

simulation:
  duration: 10.0
  arrangement: foam_die1

  static_obstacles:
    enabled: true
    urdf:
      package: "upright_assets"
      path: "thing/urdf/obstacles.urdf"
      includes:
        - "$(find upright_assets)/thing/xacro/obstacles/simple.urdf.xacro"

controller:
  balancing:
    enabled: true
    use_force_constraints: true
    arrangement: foam_die1
    constraint_type: hard
    enable_normal_constraint: true
    enable_friction_constraint: true
    enable_zmp_constraint: true

  obstacles:
    enabled: true
    constraint_type: hard
    minimum_distance: 0.1

  # final position can be done with either base or arm only
  waypoints:
    # -
    #   time: 0
    #   position: [2.0, 0, -0.25]
    #   orientation: [0, 0, 0, 1]
    # -
    #   time: 0
    #   position: [0.0, -2.0, -0.25]
    #   orientation: [0, 0, 0, 1]
    -
      time: 0
      position: [-2.0, 1.0, 0]
      orientation: [0, 0, 0, 1]
