# these values are either updated by the simulation environment or by Vicon
dynamic:
  -
    name: dynobs1
    # NOTE: these are *initial conditions*. In real experiment, the position is
    # relative to the origin of the world frame. In simulation, position and
    # velocity are (typically) (re-)set by the simulator for maximum accuracy.
    position: [0, -10, 0]  # out of the way
    velocity: [0, 0, 0]
    acceleration: [0, 0, -9.81]
    radius: 0.1

collision_pairs:
  # wrist and shoulder
  # - ["wrist1_collision_link_0", "shoulder_collision_link_0"]

  # arm and dynamic obstacles
  - ["balanced_object_collision_link_0", "dynobs1"]
  - ["wrist3_collision_link_0", "dynobs1"]

