dynamic:
  -
    name: dynobs1
    position: [0, -1, 0]
    velocity: [0, 2, 0]
    acceleration: [0, 0, 0]
    radius: 0.1

collision_pairs:
  # wrist and shoulder
  # - ["wrist1_collision_link_0", "shoulder_collision_link_0"]

  # arm and dynamic obstacles
  - ["balanced_object_collision_link_0", "dynobs1"]
  - ["wrist3_collision_link_0", "dynobs1"]

