include:
  -
    key: simulation
    package: upright_robust
    path: config/simulation.yaml
  -
    key: controller
    package: upright_robust
    path: config/controller.yaml
  -
    package: upright_cmd
    path: config/robots/thing.yaml

logging:
  timestep: 0.010
  log_dir: /media/adam/Data/PhD/Data/upright/robust

controller:
  balancing:
    enabled: false
    use_force_constraints: true

  waypoints:
    -
      time: 0
      position: [0, 0, 0]  # stay still
      orientation: [0, 0, 0, 1]
