include:
  -
    key: simulation
    package: upright_robust
    path: config/simulation.yaml
  -
    key: controller
    package: upright_robust
    path: config/controller.yaml
  -
    package: upright_cmd
    path: config/robots/thing.yaml

logging:
  timestep: 0.010
  log_dir: /media/adam/Data/PhD/Data/upright/robust/heins-ral24/simulations

simulation:
  duration: 12.0
  extra_gui: false
  robot:
    urdf:
      includes:
        - "$(find mobile_manipulation_central)/urdf/xacro/cartesian_base_joints.urdf.xacro"
        - "$(find mobile_manipulation_central)/urdf/xacro/thing_no_wheels.urdf.xacro"
        - "$(find upright_assets)/thing/xacro/end_effectors/gripped_object.urdf.xacro"
      args:
        transform_params: "$(find upright_cmd)/config/robots/calibration/tray_transforms_real.yaml"

  cameras:
    camera1:
      target: [1.04, 2.26, 0.92]
      distance: 1
      roll: 0
      pitch: -17.8
      yaw: 91.2

  video:
    save_frames: true
    dir: /media/adam/Data/PhD/Data/upright/robust/videos
    timestep: 0.040
    views:
      -
        camera: camera1
        name: view1

controller:
  robot:
    urdf:
      args:
        use_collision: "true"
        transform_params: "$(find upright_cmd)/config/robots/calibration/tray_transforms_real.yaml"

  mpc:
    time_horizon: 10.0

  sqp:
    sqp_iteration: 1
    init_sqp_iteration: 3
    hpipm:
      iter_max: 30
      warm_start: 1
      slacks:
        enabled: true
        input_box: false
        state_box: true
        poly_ineq: true
        # upper_L2_penalty: 1
        # lower_L2_penalty: 1
        # upper_L1_penalty: 1
        # lower_L1_penalty: 1

  balancing:
    enabled: true
    frictionless: true
    # force_weight: 0.001
    force_weight: 0.0

  weights:
    input:
      scale: 0.001
      diag: [1rep9]
    state:
      scale: 0.01
      diag: [0rep9, 10rep9, 1rep9]
    end_effector:
      scale: 1
      diag: [1, 1, 1, 0, 0, 0]

  # waypoints:
  #   -
  #     time: 0
  #     # position: [-2.0, 1.0, 0]  # point 1
  #     position: [0.0, -2.0, 0.25]  # point 3
  #     orientation: [0, 0, 0, 1]
