include:
  -
    package: upright_robust
    path: config/demos/_base.yaml

simulation:
  arrangement: brown_cardboard_box2_nominal

controller:
  balancing:
    arrangement: brown_cardboard_box2_nominal
