include:
  -
    package: upright_robust
    path: config/demos/_base.yaml

simulation:
  arrangement: white_cardboard_box3_nominal

controller:
  balancing:
    arrangement: white_cardboard_box3_nominal
