include:
  -
    key: simulation
    package: upright_cmd
    path: config/simulation.yaml
  -
    key: controller
    package: upright_cmd
    path: config/controller.yaml
  -
    package: upright_cmd
    path: config/ur10/ur10.yaml

logging:
  timestep: 0.010
  log_dir: /media/adam/Data/PhD/Data/upright/bounded

simulation:
  duration: 5.0
  arrangement: one_box

controller:
  balancing:
    arrangement: one_box
    enabled: true
    use_force_constraints: true
    enable_normal_constraint: true
    enable_friction_constraint: true
    enable_zmp_constraint: true

    # mu: 1e-1
    # delta: 1e-3

  tracking:
    rate: 125
    Kp:
      scale: 1
      diag: [1, 1, 1, 1, 1, 1]

  waypoints:
    -
      time: 0
      position: [-0.25, 0.5, 0.25]
      orientation: [0, 0, 0, 1]

  operating_points:
    enabled: false
    package: upright_sim
    path: trajectories/unconstrained_trajectory.npz
