include:
  -
    package: upright_robust
    path: config/demos/_base.yaml
  -
    package: upright_cmd
    path: config/ral23/experiments/_point3.yaml

simulation:
  arrangement: box2_actual

controller:
  balancing:
    arrangement: box2_top_robust
