# compute a new control policy even `control_period` milliseconds
control_period: 25
use_noisy_state_to_plan: true
gravity: [0, 0, -9.81]

balancing:
  arrangement: nothing
  enabled: true
  use_bounded_constraints: true
  enable_normal_constraint: true
  enable_friction_constraint: true
  enable_zmp_constraint: true

  mu: 1e-2
  delta: 1e-3

# desired waypoints are set relative to the initial EE pose
# each waypoint consists of:
#   millis: time from beginning of trajectory in milliseconds
#   position: [x, y, z] end effector position
#   orientation: [x, y, z, w] end effector orientation quaternion
# waypoints:
#   -
#     millis: 0
#     position: [2.0, 0.0, 0.0]
#     orientation: [0.0, 0.0, 0.0, 1.0]

static_obstacles:
  enabled: false
  urdf:
    package: "tray_balance_assets"
    path: "urdf/obstacles.urdf"

dynamic_obstacles:
  enabled: false

infofile:
  package: "tray_balance_ocs2"
  path: "config/mpc/task.info"

# arrangements reference the objects below
arrangements:
  nothing: []
  one:
    -
      name: "cylinder_stack_base"
  two:
    -
      name: "cylinder_stack_base"
    -
      name: "cuboid1_stack"
      parent: "cylinder_stack_base"
      offset:
        x: 0
        y: 0
  cups_flat:
    -
      name: tray
      type: tray
    -
      name: cup1
      type: cup
      parent: tray
      offset:
        r: 0.08
        θ: 0
    -
      name: cup2
      type: cup
      parent: tray
      offset:
        r: 0.08
        θ: 0.667pi
    -
      name: cup3
      type: cup
      parent: tray
      offset:
        r: 0.08
        θ: 1.333pi
  cups_stack:
    -
      name: tray
      type: tray
    -
      name: cup1
      type: cup
      parent: tray
    -
      name: cup2
      type: cup
      parent: cup1
    -
      name: cup3
      type: cup
      parent: cup2
  one_box:
    -
      name: box1
      type: box
  boxes_stack:
    -
      name: tray
      type: tray
    -
      name: box1
      type: box
      parent: tray
    -
      name: box2
      type: box
      parent: box1
    -
      name: box3
      type: box
      parent: box2
    -
      name: box4
      type: box
      parent: box3
  short:
    -
      name: tray
      type: tray
    -
      name: box
      type: box
      parent: tray
  tall:
    -
      name: tray
      type: tray
    -
      name: box
      type: tall_box
      parent: tray

# TODO: ideally would be able to extend other objects for easy experimentation
objects:
  ee:
    height: 0.04
    mu: 1.0

  tray:
    mass:
      min: 0.5
      max: 0.5
    com:
      height: 0.01
      half_lengths: [0.0, 0.0, 0.0]
    radii_of_gyration:
      use_exact:
        shape: cylinder
        height: 0.02
        radius: 0.2
    mu_min: 0.5
    support_area:
      shape: "circle"
      radius: 0.2
    height: 0.02

  cup:
    mass:
      min: 0.5
      max: 0.5
    com:
      height: 0.1
      half_lengths: [0.0, 0.0, 0.0]
    radii_of_gyration:
      use_exact:
        shape: cylinder
        height: 0.2
        radius: 0.04
    mu_min: 0.5
    support_area:
      shape: "circle"
      radius: 0.04
    height: 0.2

  box:
    mass:
      min: 1.0
      max: 1.0
    com:
      height: 0.1
      half_lengths: [0.0, 0.0, 0.0]
    radii_of_gyration:
      use_exact:
        shape: cuboid
        side_lengths: [0.08, 0.08, 0.15]
    mu_min: 0.5
    support_area:
      shape: "rect"
      lx: 0.08
      ly: 0.08
    height: 0.15

  tall_box:
    mass:
      min: 1.0
      max: 1.0
    com:
      height: 0.25
      half_lengths: [0.0, 0.0, 0.0]
    radii_of_gyration:
      use_exact:
        shape: cuboid
        side_lengths: [0.06, 0.06, 0.5]
    mu_min: 0.5
    support_area:
      shape: "rect"
      lx: 0.06
      ly: 0.06
    height: 0.5

  cylinder_stack_base:
    mass:
      min: 0.75
      max: 0.75
    com:
      height: 0.05
      half_lengths: [0.0, 0.0, 0.0]
    radii_of_gyration:
      use_exact:  # TODO still not sure about this format
        shape: cylinder
        height: 0.1
        radius: 0.15
      min: [0, 0, 0]
      max: [0.15, 0.15, 0.15]
    mu_min: 0.25
    support_area:
      shape: "eq_tri"
      side_length: 0.2
    height: 0.1  # this is only used to compute relative heights

  cuboid1_stack:
    mass:
      min: 0.75
      max: 0.75
    com:
      height: 0.075
      half_lengths: [0.0, 0.0, 0.0]
    radii_of_gyration:
      use_exact:
        shape: cuboid
        side_lengths: [0.15, 0.15, 0.15]
      min: [0, 0, 0]
      max: [0.075, 0.075, 0.075]
    mu_min: 0.25
    support_area:
      shape: "rect"
      lx: 0.15
      ly: 0.15
    height: 0.15
