control_period: 25
use_noisy_state_to_plan: true

balancing:
  arrangement: two

  enabled: true
  use_bounded_constraints: true
  enable_normal_constraint: true
  enable_friction_constraint: true
  enable_zmp_constraint: true

  mu: 1e-2
  delta: 1e-3

weights:
  input:
    scale: 0.1
    diag: [1, 1, 1, 1, 1, 1, 1, 1, 1]
  state:
    scale: 0.1
    diag: [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1]
  end_effector:
    scale: 1
    diag: [1, 1, 1, 0, 0, 1]

limits:
  input:
    lower: [-2, -2, -2, -4, -4, -4, -4, -4, -4]
    upper: [2, 2, 2, 4, 4, 4, 4, 4, 4]
  state:
    lower: [-10, -10, -10, -2pi, -2pi, -2pi, -2pi, -2pi, -2pi, -1, -1, -1, -2, -2, -2, -2, -2, -2]
    upper: [10, 10, 10, 2pi, 2pi, 2pi, 2pi, 2pi, 2pi, 1, 1, 1, 2, 2, 2, 2, 2, 2]

robot:
  dims:
    q: 9  # generalized position
    v: 9  # generalized velocity
    a: 9  # generalized acceleration
  dynamics: "todo"
  x0: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -0.75pi, -0.5pi, -0.25pi, -0.5pi, 0.5pi]
  urdf:
    package: "tray_balance_assets"
    path: "urdf/mm_ocs2.urdf"
  tool_link_name: "thing_tool"

# desired waypoints are set relative to the initial EE pose
waypoints:
  -
    millis: 0
    position: [0.0, -2.0, -0.5]
    orientation: [0.0, 0.0, 1.0, 0.0]  # (x, y, z, w) quaternion

static_obstacles:
  enabled: false
  urdf:
    package: "tray_balance_assets"
    path: "urdf/obstacles.urdf"

dynamic_obstacles:
  enabled: false

# TODO: doesn't necessarily make sense to have this here
logging:
  timestep: 10
  log_dir: /media/adam/Data/PhD/Data/object-balance/bounded

# arrangements reference the objects below
arrangements:
  two:
    -
      name: "cylinder_stack_base"
    -
      name: "cuboid1_stack"
      parent: "cylinder_stack_base"
      offset:
        x: 0
        y: 0

objects:
  ee:
    height: 0.04
    mu: 1.0

  cylinder_stack_base:
    mass:
      min: 0.75
      max: 0.75
    com:
      height: 0.05
      half_lengths: [0.05, 0.05, 0.05]
    radii_of_gyration: [0.15, 0.15, 0.15]
    mu_min: 0.25
    support_area:
      shape: "eq_tri"
      side_length: 0.2
      offset: [0, 0]
    height: 0.1  # this is only used to compute relative heights

  cuboid1_stack:
    mass:
      min: 0.75
      max: 0.75
    com:
      height: 0.075
      half_lengths: [0.03, 0.03, 0.03]
    radii_of_gyration: [0.075, 0.075, 0.075]
    mu_min: 0.25
    support_area:
      shape: "rect"
      lx: 0.15
      ly: 0.15
    height: 0.15
