control_period: 25

balancing:
  arrangement: two

  use_bounded_constraints: true  # not sure if I need this
  enable_normal_constraint: true
  enable_friction_constraint: true
  enable_zmp_constraint: true

input_cost:
  scale: 1
  diag: [1, 1, 1, 1, 1, 1, 1, 1, 1]

state_cost:
  scale: 1
  diag: todo

pose_cost:
  scale: 1
  diag: [1, 1, 1, 0, 0, 1]

static_obstacles: todo

dynamic_obstacles: todo

# configs reference the objects below
arrangements:
  two:
    -
      name: "cylinder_stack_base"
    -
      name: "cuboid1_stack"
      parent: "cylinder_stack_base"
      offset:
        x: 0
        y: 0

objects:
  ee:
    height: 0.04
    mu: 1.0

  cylinder_stack_base:
    mass:
      min: 0.75
      max: 0.75
    com:
      height: 0.05
      half_lengths: [0.05, 0.05, 0.05]
    radii_of_gyration: [0.15, 0.15, 0.15]
    mu_min: 0.5
    support_area:
      shape: "eq_tri"
      side_length: 0.2
      offset: [0, 0]
    height: 0.1  # this is only used to compute relative heights

  cuboid1_stack:
    mass:
      min: 0.75
      max: 0.75
    com:
      height: 0.075
      half_lengths: [0.05, 0.05, 0.05]
    radii_of_gyration: [0.075, 0.075, 0.075]
    mu_min: 0.25
    support_area:
      shape: "rect"
      lx: 0.15
      ly: 0.15
    height: 0.15
