include:
  -
    package: tray_balance_assets
    path: config/default.yaml

logging:
  log_dir: /home/adam/phd/reports/dec4/presentation/data

simulation:
  video:
    save_frames: true
    dir: /home/adam/phd/reports/dec4/presentation/videos
