include:
  -
    key: simulation
    package: tray_balance_assets
    path: config/simulation.yaml
  -
    key: controller
    package: tray_balance_assets
    path: config/controller.yaml

logging:
  # log data every `timestep` milliseconds
  timestep: 10

  # logs are saved to the following directory
  log_dir: /media/adam/Data/PhD/Data/object-balance/bounded
