include:
  -
    key: simulation
    package: tray_balance_assets
    path: config/simulation.yaml
  -
    key: controller
    package: tray_balance_assets
    path: config/controller.yaml
  -
    package: tray_balance_assets
    path: config/omni.yaml

logging:
  timestep: 10
  log_dir: /media/adam/Data/PhD/Data/object-balance/bounded

simulation:
  duration: 10000
  arrangement: tall

controller:
  balancing:
    arrangement: tall

  waypoints:
    -
      millis: 0
      position: [0.0, -2.0, 0.0]
      orientation: [0.0, 0.0, 1.0, 0.0]
