include:
  -
    key: simulation
    package: tray_balance_assets
    path: config/simulation.yaml
  -
    key: controller
    package: tray_balance_assets
    path: config/controller.yaml
  -
    package: tray_balance_assets
    path: config/panda.yaml

logging:
  timestep: 10
  log_dir: /media/adam/Data/PhD/Data/object-balance/bounded

simulation:
  duration: 10000
  arrangement: one_box

controller:
  balancing:
    arrangement: one_box
    enable_normal_constraint: false
    enable_friction_constraint: false
    enable_zmp_constraint: false

  waypoints:
    -
      millis: 0
      position: [-1, 0, 0.0]
      orientation: [0.0, 0.0, 0.0, 1.0]
    # -
    #   millis: 0
    #   position: [0, 0, 0.0]
    #   orientation: [0.707, 0.0, 0.0, 0.707]
    #   # orientation: [0.92387953, 0.0, 0.0, 0.38268343]
