# TODO it is probably desirable to just make everything integer values of
# milliseconds
timestep: 0.001
duration: 6.0
record_period: 10
arrangement: "two"

noise:
  use_noisy_state_to_plan: true
  q_std_dev: 0
  v_std_dev: 0
  v_cmd_std_dev: 0

photos: todo

video:
  record: false
  dir: "/media/adam/Data/PhD/Videos/heins-ral22/"
  frame_period: 40
  cameras:
    -
      camera: "foo"
      filename: "view1"

static_obstacles:
  enabled: false

dynamic_obstacles:
  enabled: false

urdf:
  robot:
    package: "tray_balance_assets"
    path: "urdf/mm_pyb.urdf"
  robot_obstacles:
    package: "tray_balance_assets"
    path: "urdf/mm_pyb_static_obs.urdf"
  obstacles:
    package: "tray_balance_assets"
    path: "urdf/obstacles.urdf"

# arrangements reference the objects below
arrangements:
  two:
    -
      name: "cylinder_stack_base"
    -
      name: "cuboid1_stack"
      parent: "cylinder_stack_base"
      offset:
        x: 0
        y: 0
  # short:
  #   -
  #     name: "tray"
  #     parent: "ee"
  #     offset:
  #       x: 0
  #       y: 0
  #   -
  #     name: "cuboid_short"
  #     parent: "tray"
  #     offset:
  #       r: 0
  #       Î¸: 0
  # tall:
  #   -
  #     name: "tray"
  #     parent: "ee"
  #   -
  #     name: "cuboid_tall"
  #     parent: "tray"


objects:
  cylinder_stack_base:
    shape: "cylinder"
    mass: 0.75
    mu: 0.5
    height: 0.1
    radius: 0.15
    color: [0, 0, 1, 1]
  cuboid1_stack:
    shape: "cuboid"
    mass: 0.75
    mu: 0.25
    side_lengths: [0.15, 0.15, 0.15]
    color: [1, 0, 0, 1]

cameras:
  -
    name: pose_to_pose_video_recorder2
    distance: 1.4
    roll: 0
    pitch: -32.2
    yaw: 91.6
    target: [1.375, -1.097, 1.039]
