# all times are in (an integer value of) milliseconds
timestep: 1
duration: 6000
gravity: [0, 0, -9.81]
arrangement: one

robot:
  home:
    base: [0, 0, 0]
    arm: [0.0, -0.75pi, -0.5pi, -0.25pi, -0.5pi, 0.5pi]  # upright
    # arm: [0.0, -0.75pi, -0.5pi, -0.75pi, -0.5pi, 0.5pi]  # standard
  noise:
    measurement:
      q_std_dev: 0
      v_std_dev: 0
    process:
      v_std_dev: 0
  joint_names:
    - "x_to_world_joint"
    - "y_to_x_joint"
    - "base_to_y_joint"
    - "ur10_arm_shoulder_pan_joint"
    - "ur10_arm_shoulder_lift_joint"
    - "ur10_arm_elbow_joint"
    - "ur10_arm_wrist_1_joint"
    - "ur10_arm_wrist_2_joint"
    - "ur10_arm_wrist_3_joint"
  tool_joint_name: "tool0_tcp_fixed_joint"

video:
  save_video: false
  save_frames: false
  dir: "/media/adam/Data/PhD/Videos/tray-balance/"
  timestep: 40
  views:
    -
      camera: pose_to_pose1
      name: view1

static_obstacles:
  enabled: false

dynamic_obstacles:
  enabled: false

urdf:
  robot:
    package: "tray_balance_assets"
    path: "urdf/mm_pyb.urdf"
  robot_obstacles:
    package: "tray_balance_assets"
    path: "urdf/mm_pyb_static_obs.urdf"
  obstacles:
    package: "tray_balance_assets"
    path: "urdf/obstacles.urdf"

# arrangements reference the objects below
arrangements:
  one:
    -
      name: "cylinder_stack_base"
  two:
    -
      name: "cylinder_stack_base"
    -
      name: "cuboid1_stack"
      parent: "cylinder_stack_base"
      offset:
        x: 0
        y: 0
  # short:
  #   -
  #     name: "tray"
  #     parent: "ee"
  #     offset:
  #       x: 0
  #       y: 0
  #   -
  #     name: "cuboid_short"
  #     parent: "tray"
  #     offset:
  #       r: 0
  #       Î¸: 0
  # tall:
  #   -
  #     name: "tray"
  #     parent: "ee"
  #   -
  #     name: "cuboid_tall"
  #     parent: "tray"


objects:
  # EE is a special object
  ee:
    height: 0.04
    mu: 1.0
  cylinder_stack_base:
    shape: "cylinder"
    mass: 0.75
    mu: 0.25
    height: 0.1
    radius: 0.15
    color: [0, 0, 1, 1]
  cuboid1_stack:
    shape: "cuboid"
    mass: 0.75
    mu: 0.25
    side_lengths: [0.15, 0.15, 0.15]
    color: [1, 0, 0, 1]

cameras:
  balance_objects:
    relative_target: [0, 0, 0.1]
    relative_position: [0.4, -1, 0.6]
  robot:
    relative_target: [-0.4, 0, -0.3]
    relative_position: [0.5, -2, 0.5]
  dynamic_obstacles1:
    target: [1.28, 0.045, 0.647]
    distance: 1.8
    roll: 0
    pitch: -29
    yaw: 147.6
  dynamic_obstacles2:
    target: [1.28, 0.045, 0.647]
    distance: 2.6
    roll: 0
    pitch: -20.6
    yaw: -3.2
  static_obstacles1:
    target: [2.77, 0.043, 0.142]
    distance: 4.8
    roll: 0
    pitch: -13.4
    yaw: 87.6
  static_obstacles2:
    target: [2.77, 0.043, 0.142]
    distance: 3.4
    roll: 0
    pitch: -23.4
    yaw: 10.0
  static_obstacles3:
    target: [1.66, -0.31, 0.03]
    distance: 3.6
    roll: 0
    pitch: -38.2
    yaw: -39.6
  pose_to_pose1:
    target: [1.28, 0.045, 0.647]
    distance: 4
    roll: 0
    pitch: -35.8
    yaw: 42
  pose_to_pose2:
    target: [1.375, -1.097, 1.039]
    distance: 1.4
    roll: 0
    pitch: -32.2
    yaw: 91.6
