# useful to split out controller such that sim and control can have different
# configs
controller:
  control_period: 25

  balancing:
    use_robust_constraints: false
    nominal:
      enable_normal_constraint: true
      enable_friction_constraint: true
      enable_zmp_constraint: true
      config: todo
    robust:
      num_spheres: 1

  static_obstacles: todo

  dynamic_obstacles: todo

simulation:
  timestep: 0.001
  duration: 6.0
  record_period: 10
  config: "name"

  noise:
    use_noisy_state_to_plan: true
    q_std_dev: 0
    v_std_dev: 0
    v_cmd_std_dev: 0

photos: todo

video:
  record: false
  dir: "/media/adam/Data/PhD/Videos/heins-ral22/"
  frame_period: 40
  cameras:
    -
      camera: "foo"
      filename: "view1"

# configs reference the objects below
# TODO offset optional
# TODO make (x, y) and (r, θ) all specifiable at once (then they can add)
configs:
  short:
    -
      name: "tray"
      parent: "ee"
      offset:
        x: 0
        y: 0
    -
      name: "cuboid_short"
      parent: "tray"
      offset:
        r: 0
        θ: 0
  tall:
    -
      name: "tray"
      parent: "ee"
    -
      name: "cuboid_tall"
      parent: "tray"


objects: todo


cameras:
  -
    name: pose_to_pose_video_recorder2
    distance: 1.4
    roll: 0
    pitch: -32.2
    yaw: 91.6
    target: [1.375, -1.097, 1.039]
