urdf:
  package: "upright_assets"
  path: "thing/urdf/obstacles.urdf"
  includes:
    - "$(find upright_assets)/thing/xacro/obstacles/simple.urdf.xacro"

# extra margin between objects
# Important: this needs to be > 0 for the resulting constraint to be
# differentiable
minimum_distance: 0.01

# check collisions between these pairs of objects
collision_pairs:
  # wrist and sphere
  - ["wrist_collision_link_0", "sphere1_link_0"]

  # base and sphere
  - ["base_collision_link_0", "sphere1_link_0"]

  # balanced objects and sphere
  - ["balanced_object_collision_link_0", "sphere1_link_0"]

  # wrist and shoulder
  - ["wrist_collision_link_0", "shoulder_collision_link_0"]
