include:
  -
    key: simulation
    package: upright_cmd
    path: config/simulation.yaml
  -
    key: controller
    package: upright_cmd
    path: config/controller.yaml
  -
    package: upright_cmd
    path: config/ridgeback/ridgeback_base.yaml

logging:
  timestep: 0.010
  log_dir: /media/adam/Data/PhD/Data/upright/bounded

simulation:
  duration: 10.0
  arrangement: foam_die1

controller:
  balancing:
    enabled: true
    use_force_constraints: true
    arrangement: foam_die1
    constraint_type: hard
    enable_normal_constraint: true
    enable_friction_constraint: true
    enable_zmp_constraint: true

  inertial_alignment:
    cost_enabled: false
    constraint_enabled: false
    use_angular_acceleration: false
    cost_weight: 1
    contact_plane_normal: [0, 0, 1]
    alpha: 0.3  # TODO tune/calculate properly
    com: [0, 0, 0]

  waypoints:
    -
      time: 0
      position: [0, 2.0, 0]
      orientation: [0, 0, 0, 1]
