include:
  -
    package: upright_robust
    path: config/demos/_base.yaml

controller:
  reactive:
    tilting: full
    robust: false
    face_form: true
    approx_robust: false

  balancing:
    enabled: true
