# NOTE: this one has trouble with L1 penalties on the slack variables; may need
# more tuning
include:
  -
    package: upright_cmd
    path: config/ral23/simulations/_base.yaml

simulation:
  arrangement: tall_box

controller:
  balancing:
    enabled: false

  inertial_alignment:
    constraint_enabled: true
    use_angular_acceleration: true
    com: [0, 0, 0.5]

  waypoints:
    -
      time: 0
      position: [0.0, -2.0, 0.25]
      orientation: [0, 0, 0, 1]
