include:
  -
    key: simulation
    package: upright_cmd
    path: config/simulation.yaml
  -
    key: controller
    package: upright_cmd
    path: config/controller.yaml
  -
    package: upright_cmd
    path: config/robots/thing.yaml
  -
    package: upright_cmd
    path: config/obstacles/simple.yaml

logging:
  timestep: 0.010
  log_dir: /media/adam/Data/PhD/Data/upright/bounded

simulation:
  duration: 10.0
  arrangement: foam_die1

  static_obstacles:
    enabled: true

controller:
  balancing:
    enabled: true
    use_force_constraints: true
    arrangement: foam_die1
    constraint_type: hard
    enable_normal_constraint: true
    enable_friction_constraint: true
    enable_zmp_constraint: true

  inertial_alignment:
    cost_enabled: false
    constraint_enabled: false
    use_angular_acceleration: false
    align_with_fixed_vector: false
    cost_weight: 1
    contact_plane_normal: [0, 0, 1]
    alpha: 0.0  # TODO tune/calculate properly
    com: [0, 0, 0]

  obstacles:
    enabled: true
    constraint_type: hard
    minimum_distance: 0.1

  # final position can be done with either base or arm only
  waypoints:
    # -
    #   time: 0
    #   position: [2.0, 0, -0.25]
    #   orientation: [0, 0, 0, 1]
    # -
    #   time: 0
    #   position: [0.0, -2.0, -0.25]
    #   orientation: [0, 0, 0, 1]
    -
      time: 0
      position: [-2.0, 1.0, 0]
      orientation: [0, 0, 0, 1]
