include:
  -
    package: upright_robust
    path: config/demos/robust_approx/_base.yaml

simulation:
  arrangement: stack2_mass_certain

controller:
  balancing:
    arrangement: stack2_mass_certain
