arrangements:
  nothing:
    objects: []

  stack3:
    objects:
      -
        name: cube1
        type: stack_cube_red
        parent: ee
      -
        name: cube2
        type: stack_cube_blue_offset
        parent: cube1
      -
        name: cube3
        type: stack_cube_red_offset
        parent: cube2
    contacts:
      -
        first: ee
        second: cube1
        mu: 0.2
      -
        first: cube1
        second: cube2
        mu: 0.2
      -
        first: cube2
        second: cube3
        mu: 0.2

  stack4:
    objects:
      -
        name: cube1
        type: stack_cube_red_offset
        parent: ee
      -
        name: cube2
        type: stack_cube_blue_offset
        parent: cube1
      -
        name: cube3
        type: stack_cube_red_offset
        parent: cube2
      -
        name: cube4
        type: stack_cube_blue_offset
        parent: cube3
    contacts:
      -
        first: ee
        second: cube1
        mu: 0.5
      -
        first: cube1
        second: cube2
        mu: 0.5
      -
        first: cube2
        second: cube3
        mu: 0.5
      -
        first: cube3
        second: cube4
        mu: 0.5

  stack5:
    objects:
      -
        name: cube1
        type: stack_cube_red_offset
        parent: ee
      -
        name: cube2
        type: stack_cube_blue_offset
        parent: cube1
      -
        name: cube3
        type: stack_cube_red_offset
        parent: cube2
      -
        name: cube4
        type: stack_cube_blue_offset
        parent: cube3
      -
        name: cube5
        type: stack_cube_red_offset
        parent: cube4
    contacts:
      -
        first: ee
        second: cube1
        mu: 0.2
      -
        first: cube1
        second: cube2
        mu: 0.2
      -
        first: cube2
        second: cube3
        mu: 0.2
      -
        first: cube3
        second: cube4
        mu: 0.2
      -
        first: cube4
        second: cube5
        mu: 0.2

  single_cube:
    objects:
      -
        name: cube1
        type: stack_cube
        parent: ee
    contacts:
      -
        first: ee
        second: cube1
        mu: 0.1
        mu_margin: 0.01

  tall:
    objects:
      -
        name: block1
        type: tall_block
        parent: ee
    contacts:
      -
        first: ee
        second: block1
        mu: 0.5
        support_area_inset: 0.0

  tall_offset:
    objects:
      -
        name: block1
        type: tall_block_offset
        parent: ee
    contacts:
      -
        first: ee
        second: block1
        mu: 0.5
        support_area_inset: 0.0

  very_tall:
    objects:
      -
        name: block1
        type: very_tall_block
        parent: ee
    contacts:
      -
        first: ee
        second: block1
        mu: 0.5
        support_area_inset: 0.0

  asymmetric_arch:
    objects:
      -
        name: narrow
        type: narrow_strut
        parent: ee
        offset:
          y: -0.095
      -
        name: wide
        type: wide_strut
        parent: ee
        offset:
          y: 0.05
      -
        name: bridge
        type: bridge
        parent: wide
        offset:
          y: -0.05
    contacts:
      -
        first: ee
        second: narrow
        mu: 0.2
      -
        first: ee
        second: wide
        mu: 0.2
      -
        first: wide
        second: bridge
        mu: 0.2
      -
        first: narrow
        second: bridge
        mu: 0.2
