arrangements:
  nothing:
    objects: []

  stack4_0:
    objects:
      -
        name: cube1
        type: stack4_cube_red_0
        parent: ee
      -
        name: cube2
        type: stack4_cube_blue_0
        parent: cube1
      -
        name: cube3
        type: stack4_cube_red_0
        parent: cube2
      -
        name: cube4
        type: stack4_cube_blue_0
        parent: cube3
    contacts:
      -
        first: ee
        second: cube1
        mu: 0.5
      -
        first: cube1
        second: cube2
        mu: 0.5
      -
        first: cube2
        second: cube3
        mu: 0.5
      -
        first: cube3
        second: cube4
        mu: 0.5

  stack4_0.03:
    objects:
      -
        name: cube1
        type: stack4_cube_red_0.03
        parent: ee
      -
        name: cube2
        type: stack4_cube_blue_0.03
        parent: cube1
      -
        name: cube3
        type: stack4_cube_red_0.03
        parent: cube2
      -
        name: cube4
        type: stack4_cube_blue_0.03
        parent: cube3
    contacts:
      -
        first: ee
        second: cube1
        mu: 0.5
      -
        first: cube1
        second: cube2
        mu: 0.5
      -
        first: cube2
        second: cube3
        mu: 0.5
      -
        first: cube3
        second: cube4
        mu: 0.5

  stack4_0.04:
    objects:
      -
        name: cube1
        type: stack4_cube_red_0.04
        parent: ee
      -
        name: cube2
        type: stack4_cube_blue_0.04
        parent: cube1
      -
        name: cube3
        type: stack4_cube_red_0.04
        parent: cube2
      -
        name: cube4
        type: stack4_cube_blue_0.04
        parent: cube3
    contacts:
      -
        first: ee
        second: cube1
        mu: 0.5
      -
        first: cube1
        second: cube2
        mu: 0.5
      -
        first: cube2
        second: cube3
        mu: 0.5
      -
        first: cube3
        second: cube4
        mu: 0.5

  stack2_mass_uncertain:
    objects:
      -
        name: block1
        type: stack2_block_bottom_mass_uncertain
        parent: ee
      -
        name: block2
        type: stack2_block_top_mass_uncertain
        parent: block1
    contacts:
      -
        first: ee
        second: block1
        mu: 0.5
      -
        first: block1
        second: block2
        mu: 0.5

  stack2_mass_certain:
    objects:
      -
        name: block1
        type: stack2_block_bottom_mass_certain
        parent: ee
      -
        name: block2
        type: stack2_block_top_mass_certain
        parent: block1
    contacts:
      -
        first: ee
        second: block1
        mu: 0.5
      -
        first: block1
        second: block2
        mu: 0.5

  tall_0:
    objects:
      -
        name: block1
        type: tall_block_0
        parent: ee
    contacts:
      -
        first: ee
        second: block1
        mu: 0.5
        support_area_inset: 0.0

  tall_0.03:
    objects:
      -
        name: block1
        type: tall_block_0.03
        parent: ee
    contacts:
      -
        first: ee
        second: block1
        mu: 0.5
        support_area_inset: 0.0

  tall_0.04:
    objects:
      -
        name: block1
        type: tall_block_0.04
        parent: ee
    contacts:
      -
        first: ee
        second: block1
        mu: 0.5
        support_area_inset: 0.0

  tall_I0:
    objects:
      -
        name: block1
        type: tall_block_I0
        parent: ee
    contacts:
      -
        first: ee
        second: block1
        mu: 0.5
        support_area_inset: 0.0

  short:
    objects:
      -
        name: cube1
        type: stack4_cube_red_0
        parent: ee
    contacts:
      -
        first: ee
        second: cube1
        mu: 0.1
        mu_margin: 0.0

  very_tall:
    objects:
      -
        name: block1
        type: very_tall_block
        parent: ee
    contacts:
      -
        first: ee
        second: block1
        mu: 0.5
        support_area_inset: 0.0

  asymmetric_arch:
    objects:
      -
        name: narrow
        type: narrow_strut
        parent: ee
        offset:
          y: -0.095
      -
        name: wide
        type: wide_strut
        parent: ee
        offset:
          y: 0.05
      -
        name: bridge
        type: bridge
        parent: wide
        offset:
          y: -0.05
    contacts:
      -
        first: ee
        second: narrow
        mu: 0.2
      -
        first: ee
        second: wide
        mu: 0.2
      -
        first: wide
        second: bridge
        mu: 0.2
      -
        first: narrow
        second: bridge
        mu: 0.2
