arrangements:
  nothing:
    objects: []

  box3_actual:
    objects:
      -
        name: box
        type: box3_actual
        parent: ee
        offset:
          x: 0.065
    contacts:
      -
        first: ee
        second: box
        mu: 0.2
        support_area_inset: 0.0

  box3_center:
    objects:
      -
        name: box
        type: box3_center
        parent: ee
        offset:
          x: 0.065
    contacts:
      -
        first: ee
        second: box
        mu: 0.2
        support_area_inset: 0.0

  box3_top:
    objects:
      -
        name: box
        type: box3_top
        parent: ee
        offset:
          x: 0.065
    contacts:
      -
        first: ee
        second: box
        mu: 0.2
        support_area_inset: 0.0

  box3_robust:
    objects:
      -
        name: box1
        type: box3_1
        parent: ee
        offset:
          x: 0.065
      -
        name: box2
        type: box3_2
        parent: ee
        offset:
          x: 0.065
      -
        name: box3
        type: box3_3
        parent: ee
        offset:
          x: 0.065
      -
        name: box4
        type: box3_4
        parent: ee
        offset:
          x: 0.065
      -
        name: box5
        type: box3_5
        parent: ee
        offset:
          x: 0.065
      -
        name: box6
        type: box3_6
        parent: ee
        offset:
          x: 0.065
      -
        name: box7
        type: box3_7
        parent: ee
        offset:
          x: 0.065
      -
        name: box8
        type: box3_8
        parent: ee
        offset:
          x: 0.065
    contacts:
      -
        first: ee
        second: box1
        mu: 0.2
        support_area_inset: 0.0
      -
        first: ee
        second: box2
        mu: 0.2
        support_area_inset: 0.0
      -
        first: ee
        second: box3
        mu: 0.2
        support_area_inset: 0.0
      -
        first: ee
        second: box4
        mu: 0.2
        support_area_inset: 0.0
      -
        first: ee
        second: box5
        mu: 0.2
        support_area_inset: 0.0
      -
        first: ee
        second: box6
        mu: 0.2
        support_area_inset: 0.0
      -
        first: ee
        second: box7
        mu: 0.2
        support_area_inset: 0.0
      -
        first: ee
        second: box8
        mu: 0.2
        support_area_inset: 0.0

  box2_nominal:
    objects:
      -
        name: box
        type: box2
        parent: ee
        offset:
          x: 0.065
    contacts:
      -
        first: ee
        second: box
        mu: 0.2
        support_area_inset: 0.0

  box2_robust:
    objects:
      -
        name: box1
        type: box2_1
        parent: ee
        offset:
          x: 0.065
      -
        name: box2
        type: box2_2
        parent: ee
        offset:
          x: 0.065
      -
        name: box3
        type: box2_3
        parent: ee
        offset:
          x: 0.065
      -
        name: box4
        type: box2_4
        parent: ee
        offset:
          x: 0.065
    contacts:
      -
        first: ee
        second: box1
        mu: 0.3
        support_area_inset: 0
      -
        first: ee
        second: box2
        mu: 0.3
        support_area_inset: 0
      -
        first: ee
        second: box3
        mu: 0.3
        support_area_inset: 0
      -
        first: ee
        second: box4
        mu: 0.3
        support_area_inset: 0

