arrangements:
  nothing:
    objects: []

  tall_0:
    objects:
      -
        name: block1
        type: tall_block_0
        parent: ee
        offset:
          x: 0.0525
    contacts:
      -
        first: ee
        second: block1
        mu: 0.2
        support_area_inset: 0.0
