include:
  -
    package: upright_cmd
    path: config/controller.yaml
  -
    package: upright_robust
    path: config/arrangements.yaml

reactive:
  tilting: full  # tray | full | flat
  robust: false
  face_form: false

balancing:
  enabled: true

objects:
  # these are all the same from the controller's perspective
  stack_cube:
    mass: 0.1
    com_offset: [0, 0, 0]
    shape:
        type: cuboid
        side_lengths: [0.1, 0.1, 0.1]

  stack_cube_heavy:
    mass: 0.1
    com_offset: [0, 0, 0]
    shape:
      type: cuboid
      side_lengths: [0.1, 0.1, 0.1]

  stack_cube_light:
    mass: 0.1
    com_offset: [0, 0, 0]
    shape:
      type: cuboid
      side_lengths: [0.1, 0.1, 0.1]

  tall_block:
    mass: 0.5
    com_offset: [0, 0, 0]
    shape:
        type: cuboid
        side_lengths: [0.1, 0.1, 0.6]

    # bounds are all relative to the nominal values above
    bounds:
      com_lower: [-0.02, -0.02, -0.02]
      com_upper: [0.02, 0.02, 0.02]
      mass_lower: 0
      mass_upper: 0
