include:
  -
    package: upright_cmd
    path: config/controller.yaml
  -
    package: upright_robust
    path: config/arrangements.yaml

balancing:
  enabled: true

objects:
  box3_center:
    mass: 1
    com_offset: [0, 0, 0]
    shape: cuboid
    side_lengths: [0.155, 0.155, 0.84]

  box3_top:
    mass: 1
    com_offset: [0, 0, 0.42]
    shape: cuboid
    side_lengths: [0.155, 0.155, 0.84]

  box3_1:
    mass: 1
    com_offset: [0.05, 0.05, 0.42]
    shape: cuboid
    side_lengths: [0.155, 0.155, 0.84]

  box3_2:
    mass: 1
    com_offset: [0.05, -0.05, 0.42]
    shape: cuboid
    side_lengths: [0.155, 0.155, 0.84]

  box3_3:
    mass: 1
    com_offset: [-0.05, 0.05, 0.42]
    shape: cuboid
    side_lengths: [0.155, 0.155, 0.84]

  box3_4:
    mass: 1
    com_offset: [-0.05, -0.05, 0.42]
    shape: cuboid
    side_lengths: [0.155, 0.155, 0.84]

  box3_5:
    mass: 1
    com_offset: [0.05, 0.05, -0.42]
    shape: cuboid
    side_lengths: [0.155, 0.155, 0.84]

  box3_6:
    mass: 1
    com_offset: [0.05, -0.05, -0.42]
    shape: cuboid
    side_lengths: [0.155, 0.155, 0.84]

  box3_7:
    mass: 1
    com_offset: [-0.05, 0.05, -0.42]
    shape: cuboid
    side_lengths: [0.155, 0.155, 0.84]

  box3_8:
    mass: 1
    com_offset: [-0.05, -0.05, -0.42]
    shape: cuboid
    side_lengths: [0.155, 0.155, 0.84]

