include:
  -
    package: upright_cmd
    path: config/controller.yaml
  -
    package: upright_robust
    path: config/arrangements.yaml

reactive:
  tilting: full  # tray | full | flat
  robust: false
  face_form: false
  approx_robust: false
  use_slack: true  # true to soften EE acceleration kinematics with slack variables
  slack_weight: 10

  # rotational control gains
  kθ: 1.0
  kω: 2.0

  # linear control gains
  kp: 1.0
  kv: 2.0

balancing:
  enabled: true

objects:
  # these are all the same from the controller's perspective
  stack4_cube_red_0:
    mass: 0.25
    com_offset: [0, 0, 0]
    inertia_diag: [0.0002166667, 0.0004166667, 0.0002166667]
    shape: cuboid
    side_lengths: [0.1, 0.1, 0.1]
    bounds:
      com_lower: [-0.04, -0.04, -0.04]
      com_upper: [0.04, 0.04, 0.04]
      mass_lower: 0
      mass_upper: 0

  stack4_cube_blue_0:
    mass: 0.25
    com_offset: [0, 0, 0]
    inertia_diag: [0.0002166667, 0.0004166667, 0.0002166667]
    shape: cuboid
    side_lengths: [0.1, 0.1, 0.1]
    bounds:
      com_lower: [-0.04, -0.04, -0.04]
      com_upper: [0.04, 0.04, 0.04]
      mass_lower: 0
      mass_upper: 0

  stack4_cube_red_0.03:
    mass: 0.25
    com_offset: [0, 0, 0]
    inertia_diag: [0.0002166667, 0.0004166667, 0.0002166667]
    shape: cuboid
    side_lengths: [0.1, 0.1, 0.1]
    bounds:
      com_lower: [-0.04, -0.04, -0.04]
      com_upper: [0.04, 0.04, 0.04]
      mass_lower: 0
      mass_upper: 0

  stack4_cube_blue_0.03:
    mass: 0.25
    com_offset: [0, 0, 0]
    inertia_diag: [0.0002166667, 0.0004166667, 0.0002166667]
    shape: cuboid
    side_lengths: [0.1, 0.1, 0.1]
    bounds:
      com_lower: [-0.04, -0.04, -0.04]
      com_upper: [0.04, 0.04, 0.04]
      mass_lower: 0
      mass_upper: 0

  stack4_cube_red_0.04:
    mass: 0.25
    com_offset: [0, 0, 0]
    inertia_diag: [0.0002166667, 0.0004166667, 0.0002166667]
    shape: cuboid
    side_lengths: [0.1, 0.1, 0.1]
    bounds:
      com_lower: [-0.04, -0.04, -0.04]
      com_upper: [0.04, 0.04, 0.04]
      mass_lower: 0
      mass_upper: 0

  stack4_cube_blue_0.04:
    mass: 0.25
    com_offset: [0, 0, 0]
    inertia_diag: [0.0002166667, 0.0004166667, 0.0002166667]
    shape: cuboid
    side_lengths: [0.1, 0.1, 0.1]
    bounds:
      com_lower: [-0.04, -0.04, -0.04]
      com_upper: [0.04, 0.04, 0.04]
      mass_lower: 0
      mass_upper: 0

  stack2_block_bottom_mass_uncertain:
    mass: 0.5
    com_offset: [0, 0.0, 0]
    shape: cuboid
    side_lengths: [0.1, 0.1, 0.25]
    bounds:
      com_lower: [-0.04, -0.04, -0.04]
      com_upper: [0.04, 0.04, 0.04]
      mass_lower: -0.3
      mass_upper: 0.3

  stack2_block_top_mass_uncertain:
    mass: 0.5
    com_offset: [0, 0.0, 0]
    shape: cuboid
    side_lengths: [0.1, 0.1, 0.25]
    bounds:
      com_lower: [-0.04, -0.04, -0.04]
      com_upper: [0.04, 0.04, 0.04]
      mass_lower: -0.3
      mass_upper: 0.3

  stack2_block_bottom_mass_certain:
    mass: 0.5
    com_offset: [0, 0.0, 0]
    shape: cuboid
    side_lengths: [0.1, 0.1, 0.25]
    bounds:
      com_lower: [-0.04, -0.04, -0.04]
      com_upper: [0.04, 0.04, 0.04]
      mass_lower: 0
      mass_upper: 0

  stack2_block_top_mass_certain:
    mass: 0.5
    com_offset: [0, 0.0, 0]
    shape: cuboid
    side_lengths: [0.1, 0.1, 0.25]
    bounds:
      com_lower: [-0.04, -0.04, -0.04]
      com_upper: [0.04, 0.04, 0.04]
      mass_lower: 0
      mass_upper: 0

  # tall_block_0:
  #   mass: 1.0
  #   com_offset: [0, 0, 0]
  #   # inertia_diag: [0.0133666667, 0.0141666667, 0.0008666667]  # uniform density
  #   inertia_diag: [0.0425, 0.0425, 0.005]  # 1kg mass spread in corners
  #   # inertia_diag: [0.0, 0.0, 0.0]
  #   shape:
  #     shape: cuboid
  #     side_lengths: [0.1, 0.1, 0.4]
  #
  #   # bounds are all relative to the nominal values above
  #   # these are the bounds actually enforced by the QP-based controller
  #   bounds_approx_inertia:
  #     com_lower: [-0.04, -0.04, -0.2]
  #     com_upper: [0.04, 0.04, 0.2]
  #     mass_lower: 0
  #     mass_upper: 0
  #
  #   # these are the bounds that allow any inertia matrix that is physically
  #   # realizable
  #   bounds_realizable:
  #     com_lower: [-0.035, -0.035, -0.1]
  #     com_upper: [0.035, 0.035, 0.1]
  #     # com_lower: [-0.04, -0.04, -0.1]
  #     # com_upper: [0.04, 0.04, 0.1]
  #     mass_lower: 0
  #     mass_upper: 0
  #
  #     ellipsoid:
  #       # half_extents: [0.05, 0.05, 0.2]  # inscribed
  #       # TODO could generate this automatically from the box
  #       half_extents: [0.08660115, 0.08660115, 0.34642127]  # bounding
  #     box:
  #       half_extents: [0.05, 0.05, 0.2]

  tall_block_0:
    mass: 1.0
    com_offset: [0, 0, 0]
    inertia_diag: [0.064, 0.064, 0.0128]  # 1kg mass spread in corners
    # inertia_diag: [0.1, 0.1, 0.1]
    # inertia_diag: [0, 0, 0]
    shape: cuboid
    side_lengths: [0.16, 0.16, 0.48]

    # bounds are all relative to the nominal values above
    # these are the bounds actually enforced by the QP-based controller
    bounds_approx_inertia:
      # com_lower: [-0.04, -0.04, -0.2]
      # com_upper: [0.04, 0.04, 0.2]
      com_lower: [0, 0, 0]
      com_upper: [0, 0, 0]
      mass_lower: 0
      mass_upper: 0

    # these are the bounds that allow any inertia matrix that is physically
    # realizable
    bounds_realizable:
      com_lower: [-0.05, -0.05, -0.2]
      com_upper: [0.05, 0.05, 0.2]
      mass_lower: 0
      mass_upper: 0

      ellipsoid:
        # TODO could generate this automatically from the box
        half_extents: [0.13856013, 0.13856013, 0.4157158]  # bounding
      box:
        half_extents: [0.08, 0.08, 0.24]

  tall_block_0.03:
    mass: 1.0
    com_offset: [0, 0, 0]
    inertia_diag: [0.0133666667, 0.0141666667, 0.0008666667]
    shape: cuboid
    side_lengths: [0.1, 0.1, 0.4]
    bounds:
      com_lower: [-0.04, -0.04, -0.04]
      com_upper: [0.04, 0.04, 0.04]
      mass_lower: 0
      mass_upper: 0

  tall_block_0.04:
    mass: 1.0
    com_offset: [0, 0, 0]
    inertia_diag: [0.0133666667, 0.0141666667, 0.0008666667]
    shape: cuboid
    side_lengths: [0.1, 0.1, 0.4]
    bounds:
      com_lower: [-0.04, -0.04, -0.04]
      com_upper: [0.04, 0.04, 0.04]
      mass_lower: 0
      mass_upper: 0

  tall_block_I0:
    mass: 1.0
    com_offset: [0, 0, 0]
    shape: cuboid
    side_lengths: [0.1, 0.1, 0.4]
    color: [1, 0, 0, 1]

  very_tall_block:
    mass: 0.5
    com_offset: [0, 0, 0]
    shape: cuboid
    side_lengths: [0.1, 0.1, 1.0]

  narrow_strut:
    mass: 0.1
    com_offset: [0, 0, 0]
    shape: cuboid
    side_lengths: [0.1, 0.01, 0.3]

  wide_strut:
    mass: 0.5
    com_offset: [0, 0, 0]
    shape: cuboid
    side_lengths: [0.1, 0.1, 0.3]

  bridge:
    mass: 0.5
    com_offset: [0, 0, 0]
    shape: cuboid
    side_lengths: [0.1, 0.2, 0.1]
