include:
  -
    package: upright_cmd
    path: config/controller.yaml
  -
    package: upright_robust
    path: config/arrangements.yaml

# NOTE: experimental new config
reactive:
  tilting: full  # tray | full
  robust: false

balancing:
  enabled: true

objects:
  # these are all the same from the controller's perspective
  stack_cube:
    mass: 0.1
    com_offset: [0, 0, 0]
    shape:
        type: cuboid
        side_lengths: [0.1, 0.1, 0.1]

  stack_cube_heavy:
    mass: 0.1
    com_offset: [0, 0, 0]
    shape:
      type: cuboid
      side_lengths: [0.1, 0.1, 0.1]

  stack_cube_light:
    mass: 0.1
    com_offset: [0, 0, 0]
    shape:
      type: cuboid
      side_lengths: [0.1, 0.1, 0.1]

  tall_block:
    mass: 0.5
    com_offset: [0, 0, 0]
    shape:
        type: cuboid
        side_lengths: [0.1, 0.1, 0.6]
