include:
  -
    package: upright_cmd
    path: config/controller.yaml
  -
    package: upright_robust
    path: config/arrangements.yaml

reactive:
  tilting: full  # tray | full | flat
  robust: false
  face_form: false
  approx_robust: false

  # rotational control gains
  kθ: 1.0
  kω: 2.0

  # linear control gains
  kp: 1.0
  kv: 2.0

balancing:
  enabled: true

objects:
  # these are all the same from the controller's perspective
  stack_cube:
    mass: 0.1
    com_offset: [0, 0, 0]
    shape:
        type: cuboid
        side_lengths: [0.1, 0.1, 0.1]

  stack_cube_red:
    mass: 0.1
    com_offset: [0, 0, 0]
    shape:
        type: cuboid
        side_lengths: [0.1, 0.1, 0.1]

  stack_cube_blue:
    mass: 0.1
    com_offset: [0, 0, 0]
    shape:
        type: cuboid
        side_lengths: [0.1, 0.1, 0.1]

  stack_cube_red_offset:
    mass: 0.1
    com_offset: [0, 0, 0]
    shape:
        type: cuboid
        side_lengths: [0.1, 0.1, 0.1]

    bounds:
      com_lower: [-0.04, -0.04, -0.04]
      com_upper: [0.04, 0.04, 0.04]
      mass_lower: 0
      mass_upper: 0

  stack_cube_blue_offset:
    mass: 0.1
    com_offset: [0, 0, 0]
    shape:
        type: cuboid
        side_lengths: [0.1, 0.1, 0.1]

    bounds:
      com_lower: [-0.04, -0.04, -0.04]
      com_upper: [0.04, 0.04, 0.04]
      mass_lower: 0
      mass_upper: 0

  stack_cube_heavy:
    mass: 0.1
    com_offset: [0, 0, 0]
    shape:
      type: cuboid
      side_lengths: [0.1, 0.1, 0.1]

  stack_cube_light:
    mass: 0.1
    com_offset: [0, 0, 0]
    shape:
      type: cuboid
      side_lengths: [0.1, 0.1, 0.1]

  tall_block:
    mass: 0.5
    com_offset: [0, 0, 0]
    shape:
      type: cuboid
      side_lengths: [0.1, 0.1, 0.4]

    # bounds are all relative to the nominal values above
    bounds:
      com_lower: [-0.04, -0.04, -0.04]
      com_upper: [0.04, 0.04, 0.04]
      mass_lower: 0
      mass_upper: 0

  very_tall_block:
    mass: 0.5
    com_offset: [0, 0, 0]
    shape:
        type: cuboid
        side_lengths: [0.1, 0.1, 1.0]

  narrow_strut:
    mass: 0.1
    com_offset: [0, 0, 0]
    shape:
      type: cuboid
      side_lengths: [0.1, 0.01, 0.3]

  wide_strut:
    mass: 0.5
    com_offset: [0, 0, 0]
    shape:
      type: cuboid
      side_lengths: [0.1, 0.1, 0.3]

  bridge:
    mass: 0.5
    com_offset: [0, 0, 0]
    shape:
      type: cuboid
      side_lengths: [0.1, 0.2, 0.1]
