include:
  -
    package: upright_cmd
    path: config/simulation.yaml
  -
    package: upright_robust
    path: config/arrangements.yaml

duration: 10.0

objects:
  stack_cube:
    shape: cuboid
    mass: 0.01
    side_lengths: [0.1, 0.1, 0.2]
    color: [1, 0, 0, 1]

  stack_cube_heavy:
    shape: cuboid
    mass: 1
    side_lengths: [0.1, 0.1, 0.2]
    color: [1, 0, 0, 1]

  stack_cube_light:
    shape: cuboid
    mass: 0.01
    side_lengths: [0.1, 0.1, 0.2]
    color: [1, 0, 0, 1]

  tall_block:
    mass: 0.5
    com_offset: [0, 0, 0.2]
    shape: cuboid
    side_lengths: [0.1, 0.1, 0.5]
    color: [1, 0, 0, 1]
