include:
  -
    package: upright_cmd
    path: config/simulation.yaml
  -
    package: upright_robust
    path: config/arrangements.yaml

objects:
  stack_cube:
    shape: cuboid
    mass: 0.1
    side_lengths: [0.1, 0.1, 0.1]
    color: [1, 0, 0, 1]

  stack_cube_heavy:
    shape: cuboid
    mass: 0.1
    side_lengths: [0.1, 0.1, 0.1]
    color: [1, 0, 0, 1]

  stack_cube_light:
    shape: cuboid
    mass: 0.1
    side_lengths: [0.1, 0.1, 0.1]
    color: [1, 0, 0, 1]

  tall_block:
    mass: 0.5
    com_offset: [0, -0.03, 0]
    # com_offset: [0, 0, 0]
    shape: cuboid
    side_lengths: [0.1, 0.1, 0.4]
    color: [1, 0, 0, 1]
