include:
  -
    package: upright_cmd
    path: config/simulation.yaml
  -
    package: upright_robust
    path: config/arrangements.yaml

objects:
  stack_cube_red_0:
    shape: cuboid
    mass: 0.125
    inertia_diag: [0.0001083333, 0.0002083333, 0.0001083333]
    side_lengths: [0.1, 0.1, 0.1]
    color: [1, 0, 0, 1]

  stack_cube_blue_0:
    shape: cuboid
    mass: 0.125
    inertia_diag: [0.0001083333, 0.0002083333, 0.0001083333]
    side_lengths: [0.1, 0.1, 0.1]
    color: [0, 0, 1, 1]

  stack_cube_red_0.03:
    shape: cuboid
    mass: 0.125
    inertia_diag: [0.0001083333, 0.0002083333, 0.0001083333]
    com_offset: [0, -0.03, 0]
    side_lengths: [0.1, 0.1, 0.1]
    color: [1, 0, 0, 1]

  stack_cube_blue_0.03:
    shape: cuboid
    mass: 0.125
    inertia_diag: [0.0001083333, 0.0002083333, 0.0001083333]
    com_offset: [0, -0.03, 0]
    side_lengths: [0.1, 0.1, 0.1]
    color: [0, 0, 1, 1]

  stack_cube_red_0.04:
    shape: cuboid
    mass: 0.125
    inertia_diag: [0.0001083333, 0.0002083333, 0.0001083333]
    com_offset: [0, -0.04, 0]
    side_lengths: [0.1, 0.1, 0.1]
    color: [1, 0, 0, 1]

  stack_cube_blue_0.04:
    shape: cuboid
    mass: 0.125
    inertia_diag: [0.0001083333, 0.0002083333, 0.0001083333]
    com_offset: [0, -0.04, 0]
    side_lengths: [0.1, 0.1, 0.1]
    color: [0, 0, 1, 1]

  tall_block_0:
    mass: 0.5
    com_offset: [0, 0, 0]
    inertia_diag: [0.0066833333, 0.0070833333, 0.0004333333]
    shape: cuboid
    side_lengths: [0.1, 0.1, 0.4]
    color: [1, 0, 0, 1]

  tall_block_0.03:
    mass: 0.5
    com_offset: [0, -0.03, 0]
    # inertial diagonal about the CoM
    inertia_diag: [0.0066833333, 0.0070833333, 0.0004333333]
    shape: cuboid
    side_lengths: [0.1, 0.1, 0.4]
    color: [1, 0, 0, 1]

  tall_block_0.04:
    mass: 0.5
    com_offset: [0, -0.04, 0]
    inertia_diag: [0.0066833333, 0.0070833333, 0.0004333333]
    shape: cuboid
    side_lengths: [0.1, 0.1, 0.4]
    color: [1, 0, 0, 1]

  very_tall_block:
    mass: 0.5
    com_offset: [0, 0, 0]
    shape: cuboid
    side_lengths: [0.1, 0.1, 1.0]
    color: [1, 0, 0, 1]

  narrow_strut:
    mass: 0.1
    com_offset: [0, 0, 0]
    shape: cuboid
    side_lengths: [0.1, 0.01, 0.3]
    color: [1, 0, 0, 1]

  wide_strut:
    mass: 0.5
    com_offset: [0, 0, 0]
    shape: cuboid
    side_lengths: [0.1, 0.1, 0.3]
    color: [1, 0, 0, 1]

  bridge:
    mass: 0.5
    com_offset: [0, 0, 0]
    shape: cuboid
    side_lengths: [0.1, 0.2, 0.1]
    color: [1, 0, 0, 1]
