include:
  -
    package: upright_cmd
    path: config/simulation.yaml
  -
    package: upright_robust
    path: config/arrangements.yaml

objects:
  stack_cube:
    shape: cuboid
    mass: 0.1
    side_lengths: [0.1, 0.1, 0.1]
    color: [0, 0, 1, 1]

  stack_cube_red:
    shape: cuboid
    mass: 0.1
    side_lengths: [0.1, 0.1, 0.1]
    color: [1, 0, 0, 1]

  stack_cube_blue:
    shape: cuboid
    mass: 0.1
    side_lengths: [0.1, 0.1, 0.1]
    color: [0, 0, 1, 1]

  stack_cube_red_offset:
    shape: cuboid
    mass: 0.1
    com_offset: [0, -0.045, 0]
    side_lengths: [0.1, 0.1, 0.15]
    color: [1, 0, 0, 1]

  stack_cube_blue_offset:
    shape: cuboid
    mass: 0.1
    com_offset: [0, -0.045, 0]
    side_lengths: [0.1, 0.1, 0.15]
    color: [0, 0, 1, 1]

  stack_cube_heavy:
    shape: cuboid
    mass: 1.0
    side_lengths: [0.1, 0.1, 0.1]
    color: [1, 0, 0, 1]

  stack_cube_light:
    shape: cuboid
    mass: 0.1
    side_lengths: [0.1, 0.1, 0.1]
    color: [1, 0, 0, 1]

  tall_block:
    mass: 0.5
    com_offset: [0, 0, 0]
    shape: cuboid
    side_lengths: [0.1, 0.1, 0.4]
    color: [1, 0, 0, 1]

  tall_block_offset:
    mass: 0.5
    com_offset: [0, -0.04, 0]
    shape: cuboid
    side_lengths: [0.1, 0.1, 0.5]
    color: [1, 0, 0, 1]

  very_tall_block:
    mass: 0.5
    com_offset: [0, 0, 0]
    shape: cuboid
    side_lengths: [0.1, 0.1, 1.0]
    color: [1, 0, 0, 1]

  narrow_strut:
    mass: 0.1
    com_offset: [0, 0, 0]
    shape: cuboid
    side_lengths: [0.1, 0.01, 0.3]
    color: [1, 0, 0, 1]

  wide_strut:
    mass: 0.5
    com_offset: [0, 0, 0]
    shape: cuboid
    side_lengths: [0.1, 0.1, 0.3]
    color: [1, 0, 0, 1]

  bridge:
    mass: 0.5
    com_offset: [0, 0, 0]
    shape: cuboid
    side_lengths: [0.1, 0.2, 0.1]
    color: [1, 0, 0, 1]
