include:
  -
    package: upright_cmd
    path: config/simulation.yaml
  -
    package: upright_robust
    path: config/arrangements.yaml

objects:
  box3_actual:
    mass: 1.067
    # we are assuming the CoM is located at the center of the bottle
    com_offset: [0.04, -0.04, 0.24]
    # com_offset: [0.06, -0.07, 0.8]
    # assume only the bottle contributes to inertia
    inertia_diag: [0.00393178, 0.00393178, 0.00075023]
    shape: cuboid
    side_lengths: [0.15, 0.15, 0.84]
    color: [0.7, 0.53, 0.35, 1]

  box1_center:
    mass: 1
    com_offset: [0, 0, 0]
    shape: cuboid
    side_lengths: [0.15, 0.15, 0.28]
    color: [0.7, 0.53, 0.35, 1]

  box2_center:
    mass: 1
    com_offset: [0, 0, 0]
    shape: cuboid
    side_lengths: [0.15, 0.15, 0.56]
    color: [0.7, 0.53, 0.35, 1]
