include:
  -
    package: upright_cmd
    path: config/simulation.yaml
  -
    package: upright_robust
    path: config/arrangements.yaml

objects:
  # STACK4
  stack4_cube_red_0:
    shape: cuboid
    mass: 0.25
    inertia_diag: [0.0002166667, 0.0004166667, 0.0002166667]
    side_lengths: [0.1, 0.1, 0.1]
    color: [1, 0, 0, 1]

  stack4_cube_blue_0:
    shape: cuboid
    mass: 0.25
    inertia_diag: [0.0002166667, 0.0004166667, 0.0002166667]
    side_lengths: [0.1, 0.1, 0.1]
    color: [0, 0, 1, 1]

  stack4_cube_red_0.03:
    shape: cuboid
    mass: 0.25
    inertia_diag: [0.0002166667, 0.0004166667, 0.0002166667]
    com_offset: [0, -0.03, 0]
    side_lengths: [0.1, 0.1, 0.1]
    color: [1, 0, 0, 1]

  stack4_cube_blue_0.03:
    shape: cuboid
    mass: 0.25
    inertia_diag: [0.0002166667, 0.0004166667, 0.0002166667]
    com_offset: [0, -0.03, 0]
    side_lengths: [0.1, 0.1, 0.1]
    color: [0, 0, 1, 1]

  stack4_cube_red_0.04:
    shape: cuboid
    mass: 0.25
    inertia_diag: [0.0002166667, 0.0004166667, 0.0002166667]
    com_offset: [0, -0.04, 0]
    side_lengths: [0.1, 0.1, 0.1]
    color: [1, 0, 0, 1]

  stack4_cube_blue_0.04:
    shape: cuboid
    mass: 0.25
    inertia_diag: [0.0002166667, 0.0004166667, 0.0002166667]
    com_offset: [0, -0.04, 0]
    side_lengths: [0.1, 0.1, 0.1]
    color: [0, 0, 1, 1]

  # STACK2
  # the certain/uncertain variants are the same from the simulation side: only
  # the controller bounds change
  stack2_block_bottom_mass_uncertain:
    shape: cuboid
    mass: 0.2
    com_offset: [0, -0.04, 0]
    side_lengths: [0.1, 0.1, 0.25]
    color: [0, 0, 1, 1]

  stack2_block_top_mass_uncertain:
    shape: cuboid
    mass: 0.8
    com_offset: [0, -0.04, 0]
    side_lengths: [0.1, 0.1, 0.25]
    color: [1, 0, 0, 1]

  stack2_block_bottom_mass_certain:
    shape: cuboid
    mass: 0.2
    com_offset: [0, -0.04, 0]
    side_lengths: [0.1, 0.1, 0.25]
    color: [0, 0, 1, 1]

  stack2_block_top_mass_certain:
    shape: cuboid
    mass: 0.8
    com_offset: [0, -0.04, 0]
    side_lengths: [0.1, 0.1, 0.25]
    color: [1, 0, 0, 1]

  # TALL
  tall_block_0:
    mass: 1.0
    # com_offset: [0, 0, 0]
    com_offset: [0, -0.035, 0]
    # inertial diagonal about the CoM
    inertia_diag: [0.0133666667, 0.0141666667, 0.0008666667]
    shape: cuboid
    side_lengths: [0.1, 0.1, 0.4]
    color: [1, 0, 0, 1]

  tall_block_0.03:
    mass: 1.0
    com_offset: [0, -0.03, 0]
    inertia_diag: [0.0133666667, 0.0141666667, 0.0008666667]
    shape: cuboid
    side_lengths: [0.1, 0.1, 0.4]
    color: [1, 0, 0, 1]

  tall_block_0.04:
    mass: 1.0
    com_offset: [0, -0.04, 0]
    inertia_diag: [0.0133666667, 0.0141666667, 0.0008666667]
    shape: cuboid
    side_lengths: [0.1, 0.1, 0.4]
    color: [1, 0, 0, 1]

  tall_block_I0:
    mass: 1.0
    com_offset: [0, 0, 0]
    inertia_diag: [0, 0, 0]
    # inertia_diag: [0.02125, 0.02125, 0.0025]
    shape: cuboid
    side_lengths: [0.1, 0.1, 0.4]
    color: [1, 0, 0, 1]

  # MISC/EXPERIMENTAL
  very_tall_block:
    mass: 0.5
    com_offset: [0, 0, 0]
    shape: cuboid
    side_lengths: [0.1, 0.1, 1.0]
    color: [1, 0, 0, 1]

  narrow_strut:
    mass: 0.1
    com_offset: [0, 0, 0]
    shape: cuboid
    side_lengths: [0.1, 0.01, 0.3]
    color: [1, 0, 0, 1]

  wide_strut:
    mass: 0.5
    com_offset: [0, 0, 0]
    shape: cuboid
    side_lengths: [0.1, 0.1, 0.3]
    color: [1, 0, 0, 1]

  bridge:
    mass: 0.5
    com_offset: [0, 0, 0]
    shape: cuboid
    side_lengths: [0.1, 0.2, 0.1]
    color: [1, 0, 0, 1]
