# Cfg file for  Demo control environment
world:
  type: 'Real' #'Bullet' or 'Real'
  robot: 'panda'
  controlType: 'JointTorque'
data_dir: 'data'

# required by perls2 but unused
policy_freq: 500

control_freq: 1000 # Hz

logging:
  timestep: 10
  log_dir: /media/adam/Data/PhD/Data/object-balance/real-panda

# include other perls2 stuff
include:
  -
    package: upright_cmd
    path: config/panda/perls2/redis.yaml
  -
    package: upright_cmd
    path: config/panda/perls2/perls2_panda.yaml
  -
    package: upright_cmd
    path: config/panda/perls2/perls2_controller.yaml
