include:
  -
    package: upright_robust
    path: config/demos/robust_full/_base.yaml

simulation:
  arrangement: stack2_mass_uncertain

controller:
  balancing:
    arrangement: stack2_mass_uncertain
