# Cfg file for  Demo control environment
world:
  type: 'Real' #'Bullet' or 'Real'
  robot: 'panda'
  controlType: 'JointVelocity'
data_dir: 'data'

# TODO
policy_freq: 500
control_freq: 1000 # Hz

logging:
  timestep: 10
  log_dir: /media/adam/Data/PhD/Data/object-balance/real-panda

include:
  -
    package: upright_real
    path: config/redis.yaml
  -
    package: upright_real
    path: config/panda.yaml
  -
    package: upright_real
    path: config/demo_panda_controller.yaml
