# Cfg file for  Demo control environment
world:
  type: 'Real' #'Bullet' or 'Real'
  robot: 'panda'
  controlType: 'JointVelocity'
data_dir: 'data'

# TODO
policy_freq: 1000
control_freq: 1000 # Hz

# Redis config specific to this machine.
!include redis.yaml

# General Panda config
!include panda.yaml

# Controller config for each robot
!include demo_panda_controller.yaml
